// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v4.24.4
// source: distribution/search.proto

package distribution

import (
	newsdoc "github.com/ttab/elephant-api/newsdoc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language to search, as the language tag the documents are indexed
	// under, e.g. "sv" or "sv-se". Required: a query targets exactly one
	// language series so that fan-out stays explicit. An unknown language
	// is an invalid argument.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Tier to search: "recent" for the rolling recent window, "all" for
	// the recent window plus the archive. Empty defaults to "recent". Any
	// other value is an invalid argument.
	//
	// "recent" is not "whatever the cluster happens to hold locally". It
	// applies an implicit window on the document's anchor timestamp, so
	// that recent means the same thing on the first day of a quarter as on
	// the last. For document types anchored on when they happened - news,
	// and everything else dated by publication - that window is a
	// first_published no older than the configured recent window, 30 days
	// by default. Types that aren't partitioned by time, the entity
	// registries such as sections and authors, are never windowed and are
	// returned in full by both tiers.
	//
	// "all" searches the archive set as well. The archive is served from
	// snapshots mounted on separate nodes, so it answers more slowly, and
	// the higher latency is accepted rather than worked around - which is
	// why it is an explicit choice and not the default. Scope an archive
	// query with a range on the anchor field whenever you can: given a
	// range, the server resolves the query to the archived partitions that
	// intersect it instead of fanning out over every quarter ever indexed.
	//
	// A document that has been corrected after its partition was archived
	// exists in both tiers. Hits are collapsed on the document UUID, and
	// the field values reported are those of the highest indexed version,
	// so a cross-tier query never returns the same document twice and
	// never reports the superseded copy's values.
	Tier string `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	// DocumentTypes to search. Empty searches all types the caller can
	// read. A type that isn't indexed is an invalid argument.
	//
	// For a semantic query (knn) the empty list is every indexed type that
	// carries embeddings: the types that don't are skipped rather than
	// refused, since a deployment normally indexes entity registries that
	// have no vectors beside the temporal types that do. A type that is
	// named explicitly is still an invalid argument when it has no
	// embeddings - it is a question that cannot be answered, and an empty
	// result would look like one.
	DocumentTypes []string `protobuf:"bytes,3,rep,name=document_types,json=documentTypes,proto3" json:"document_types,omitempty"`
	// Query to run. An absent query matches all documents.
	Query *Query `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	// Knn is a semantic query clause: nearest neighbour search over the
	// document embeddings. See KnnQuery for how the neighbours are
	// selected.
	//
	// Combining knn with query is pre-filtering, not hybrid ranking. When
	// both are set, the translated query is applied as the *filter* of the
	// knn clause: only documents that the query matches are considered as
	// neighbour candidates, and the hits are ordered by vector similarity
	// alone. Read it as "semantic search within these filters". The query
	// contributes nothing to the score even when it is written with scoring
	// clauses such as must or should - the vector similarity is the score.
	//
	// A true hybrid that merges BM25 relevance and vector similarity into a
	// combined score is not available in this version. It is planned, and
	// it will be a separate, explicitly requested mode rather than a change
	// to what query plus knn means here, so queries written against these
	// semantics keep working.
	//
	// Only document types that are indexed with embeddings can be searched
	// this way. A knn query that names a type without vectors is an invalid
	// argument; one that names no types at all is answered from the types
	// that do have them, see document_types.
	Knn *KnnQuery `protobuf:"bytes,9,opt,name=knn,proto3" json:"knn,omitempty"`
	// Size is the maximum number of hits to return. Defaults to 50, and is
	// capped by the server.
	Size int64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// From is the number of hits to skip, for paging through a result set.
	// Deep paging is bounded by the server; use a narrower query or a sort
	// on a stable field instead of paging far into a large result.
	From int64 `protobuf:"varint,6,opt,name=from,proto3" json:"from,omitempty"`
	// Sort order of the hits. Empty sorts by relevance, descending.
	Sort []*Sort `protobuf:"bytes,7,rep,name=sort,proto3" json:"sort,omitempty"`
	// Fields to return with each hit, named as flat index fields (e.g.
	// "document.title"). Empty returns hits without field values, which is
	// the cheapest form when the caller only needs the UUIDs.
	Fields []string `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty"`
	// Generation answers the query from a named index generation instead of
	// the active one, naming it as Configuration.ListIndexGenerations does.
	// Empty is the active generation, and the only value an ordinary caller
	// may send: naming a generation requires the "dist_admin" scope.
	//
	// It is the validation surface for a rebuild or a move to another
	// cluster. A candidate generation is built and kept up to date while the
	// active one serves, and this is how real queries are pointed at it and
	// the results compared before it is activated. A generation that doesn't
	// exist, or one whose cluster is unreachable, is an error rather than a
	// silent fall back to the active generation - a comparison that quietly
	// queried the wrong index set would be worse than no comparison.
	Generation string `protobuf:"bytes,10,opt,name=generation,proto3" json:"generation,omitempty"`
	// LoadDocuments returns the document itself with each hit, as
	// Content.GetDocument would serve it: the current stored version, with
	// the rendition links generated and signed for the caller. It requires
	// the "dist_read" scope on top of the search scope - "dist_search" alone
	// grants queries over the index, not the content behind it.
	//
	// A page of hits is what bounds it - the server's page size cap applies
	// to a query that loads documents as it does to any other. A hit whose
	// document is no longer stored is returned without one rather than
	// failing the query.
	LoadDocuments bool `protobuf:"varint,11,opt,name=load_documents,json=loadDocuments,proto3" json:"load_documents,omitempty"`
	// Subset returns extracted parts of the documents instead of the whole
	// of them, as a map of newsdoc value extractors keyed by the document
	// types they apply to. It overrides load_documents for the types it
	// names, and requires the same "dist_read" scope.
	//
	// Extraction runs on the delivered document, so an extracted image block
	// carries the same generated rendition links the whole document would
	// have been served with.
	Subset map[string]*Subsets `protobuf:"bytes,12,rep,name=subset,proto3" json:"subset,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// DisableRenditionSigning serves the documents with generated but
	// unsigned rendition URLs. See
	// GetNewDocumentsRequest.disable_rendition_signing.
	DisableRenditionSigning bool `protobuf:"varint,13,opt,name=disable_rendition_signing,json=disableRenditionSigning,proto3" json:"disable_rendition_signing,omitempty"`
	// Renditions selects the rendition variants to generate per asset kind.
	// See GetNewDocumentsRequest.renditions.
	Renditions map[string]*RenditionParameters `protobuf:"bytes,14,rep,name=renditions,proto3" json:"renditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// DisableRenditions serves the documents without any rendition links.
	// See GetNewDocumentsRequest.disable_renditions.
	DisableRenditions bool `protobuf:"varint,15,opt,name=disable_renditions,json=disableRenditions,proto3" json:"disable_renditions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_distribution_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *QueryRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *QueryRequest) GetDocumentTypes() []string {
	if x != nil {
		return x.DocumentTypes
	}
	return nil
}

func (x *QueryRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryRequest) GetKnn() *KnnQuery {
	if x != nil {
		return x.Knn
	}
	return nil
}

func (x *QueryRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *QueryRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *QueryRequest) GetSort() []*Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *QueryRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *QueryRequest) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *QueryRequest) GetLoadDocuments() bool {
	if x != nil {
		return x.LoadDocuments
	}
	return false
}

func (x *QueryRequest) GetSubset() map[string]*Subsets {
	if x != nil {
		return x.Subset
	}
	return nil
}

func (x *QueryRequest) GetDisableRenditionSigning() bool {
	if x != nil {
		return x.DisableRenditionSigning
	}
	return false
}

func (x *QueryRequest) GetRenditions() map[string]*RenditionParameters {
	if x != nil {
		return x.Renditions
	}
	return nil
}

func (x *QueryRequest) GetDisableRenditions() bool {
	if x != nil {
		return x.DisableRenditions
	}
	return false
}

// Query is a single query clause. Exactly one of the conditions must be
// set; an empty Query is an invalid argument.
type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Conditions:
	//
	//	*Query_Bool
	//	*Query_Range
	//	*Query_Exists
	//	*Query_MatchAll
	//	*Query_Term
	//	*Query_Terms
	//	*Query_Match
	//	*Query_MatchPhrase
	//	*Query_QueryString
	//	*Query_Prefix
	//	*Query_MultiMatch
	Conditions    isQuery_Conditions `protobuf_oneof:"conditions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_distribution_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{1}
}

func (x *Query) GetConditions() isQuery_Conditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Query) GetBool() *BoolQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_Bool); ok {
			return x.Bool
		}
	}
	return nil
}

func (x *Query) GetRange() *RangeQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_Range); ok {
			return x.Range
		}
	}
	return nil
}

func (x *Query) GetExists() string {
	if x != nil {
		if x, ok := x.Conditions.(*Query_Exists); ok {
			return x.Exists
		}
	}
	return ""
}

func (x *Query) GetMatchAll() *MatchAllQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_MatchAll); ok {
			return x.MatchAll
		}
	}
	return nil
}

func (x *Query) GetTerm() *TermQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_Term); ok {
			return x.Term
		}
	}
	return nil
}

func (x *Query) GetTerms() *TermsQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_Terms); ok {
			return x.Terms
		}
	}
	return nil
}

func (x *Query) GetMatch() *MatchQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_Match); ok {
			return x.Match
		}
	}
	return nil
}

func (x *Query) GetMatchPhrase() *MatchPhraseQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_MatchPhrase); ok {
			return x.MatchPhrase
		}
	}
	return nil
}

func (x *Query) GetQueryString() string {
	if x != nil {
		if x, ok := x.Conditions.(*Query_QueryString); ok {
			return x.QueryString
		}
	}
	return ""
}

func (x *Query) GetPrefix() *PrefixQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_Prefix); ok {
			return x.Prefix
		}
	}
	return nil
}

func (x *Query) GetMultiMatch() *MultiMatchQuery {
	if x != nil {
		if x, ok := x.Conditions.(*Query_MultiMatch); ok {
			return x.MultiMatch
		}
	}
	return nil
}

type isQuery_Conditions interface {
	isQuery_Conditions()
}

type Query_Bool struct {
	// Bool combines subqueries.
	Bool *BoolQuery `protobuf:"bytes,1,opt,name=bool,proto3,oneof"`
}

type Query_Range struct {
	// Range matches a field against an interval.
	Range *RangeQuery `protobuf:"bytes,2,opt,name=range,proto3,oneof"`
}

type Query_Exists struct {
	// Exists matches documents that have a value for the named field.
	Exists string `protobuf:"bytes,3,opt,name=exists,proto3,oneof"`
}

type Query_MatchAll struct {
	// MatchAll matches every document.
	MatchAll *MatchAllQuery `protobuf:"bytes,4,opt,name=match_all,json=matchAll,proto3,oneof"`
}

type Query_Term struct {
	// Term matches an exact value.
	Term *TermQuery `protobuf:"bytes,5,opt,name=term,proto3,oneof"`
}

type Query_Terms struct {
	// Terms matches any of a set of exact values.
	Terms *TermsQuery `protobuf:"bytes,6,opt,name=terms,proto3,oneof"`
}

type Query_Match struct {
	// Match matches analysed text.
	Match *MatchQuery `protobuf:"bytes,7,opt,name=match,proto3,oneof"`
}

type Query_MatchPhrase struct {
	// MatchPhrase matches an analysed phrase.
	MatchPhrase *MatchPhraseQuery `protobuf:"bytes,8,opt,name=match_phrase,json=matchPhrase,proto3,oneof"`
}

type Query_QueryString struct {
	// QueryString is a query in the query string mini-language. Use it
	// for user-entered search expressions; prefer the structured clauses
	// for queries the client builds itself.
	QueryString string `protobuf:"bytes,9,opt,name=query_string,json=queryString,proto3,oneof"`
}

type Query_Prefix struct {
	// Prefix matches values that start with a value.
	Prefix *PrefixQuery `protobuf:"bytes,10,opt,name=prefix,proto3,oneof"`
}

type Query_MultiMatch struct {
	// MultiMatch matches analysed text against several fields.
	MultiMatch *MultiMatchQuery `protobuf:"bytes,11,opt,name=multi_match,json=multiMatch,proto3,oneof"`
}

func (*Query_Bool) isQuery_Conditions() {}

func (*Query_Range) isQuery_Conditions() {}

func (*Query_Exists) isQuery_Conditions() {}

func (*Query_MatchAll) isQuery_Conditions() {}

func (*Query_Term) isQuery_Conditions() {}

func (*Query_Terms) isQuery_Conditions() {}

func (*Query_Match) isQuery_Conditions() {}

func (*Query_MatchPhrase) isQuery_Conditions() {}

func (*Query_QueryString) isQuery_Conditions() {}

func (*Query_Prefix) isQuery_Conditions() {}

func (*Query_MultiMatch) isQuery_Conditions() {}

// BoolQuery combines subqueries. Must and should contribute to the
// score, filter and must_not don't.
type BoolQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must are subqueries that all have to match.
	Must []*Query `protobuf:"bytes,1,rep,name=must,proto3" json:"must,omitempty"`
	// MustNot are subqueries that must not match.
	MustNot []*Query `protobuf:"bytes,2,rep,name=must_not,json=mustNot,proto3" json:"must_not,omitempty"`
	// Should are subqueries that may match, see minimum_should_match.
	Should []*Query `protobuf:"bytes,3,rep,name=should,proto3" json:"should,omitempty"`
	// Filter are subqueries that all have to match, without affecting the
	// score of the hit.
	Filter []*Query `protobuf:"bytes,4,rep,name=filter,proto3" json:"filter,omitempty"`
	// MinimumShouldMatch is the number of should subqueries that have to
	// match. Defaults to 1 when the query has no must or filter subqueries,
	// 0 otherwise.
	MinimumShouldMatch int64 `protobuf:"varint,5,opt,name=minimum_should_match,json=minimumShouldMatch,proto3" json:"minimum_should_match,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BoolQuery) Reset() {
	*x = BoolQuery{}
	mi := &file_distribution_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolQuery) ProtoMessage() {}

func (x *BoolQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolQuery.ProtoReflect.Descriptor instead.
func (*BoolQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{2}
}

func (x *BoolQuery) GetMust() []*Query {
	if x != nil {
		return x.Must
	}
	return nil
}

func (x *BoolQuery) GetMustNot() []*Query {
	if x != nil {
		return x.MustNot
	}
	return nil
}

func (x *BoolQuery) GetShould() []*Query {
	if x != nil {
		return x.Should
	}
	return nil
}

func (x *BoolQuery) GetFilter() []*Query {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *BoolQuery) GetMinimumShouldMatch() int64 {
	if x != nil {
		return x.MinimumShouldMatch
	}
	return 0
}

// RangeQuery matches a field against an interval. The bounds are written
// as strings and parsed according to the type of the field, so a date
// field takes RFC 3339 timestamps and a numeric field takes numbers. At
// least one bound must be set; combining a lower and an upper bound gives
// a closed interval.
type RangeQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to match against.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Gt is an exclusive lower bound.
	Gt string `protobuf:"bytes,2,opt,name=gt,proto3" json:"gt,omitempty"`
	// Gte is an inclusive lower bound.
	Gte string `protobuf:"bytes,3,opt,name=gte,proto3" json:"gte,omitempty"`
	// Lt is an exclusive upper bound.
	Lt string `protobuf:"bytes,4,opt,name=lt,proto3" json:"lt,omitempty"`
	// Lte is an inclusive upper bound.
	Lte           string `protobuf:"bytes,5,opt,name=lte,proto3" json:"lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeQuery) Reset() {
	*x = RangeQuery{}
	mi := &file_distribution_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeQuery) ProtoMessage() {}

func (x *RangeQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeQuery.ProtoReflect.Descriptor instead.
func (*RangeQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{3}
}

func (x *RangeQuery) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RangeQuery) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *RangeQuery) GetGte() string {
	if x != nil {
		return x.Gte
	}
	return ""
}

func (x *RangeQuery) GetLt() string {
	if x != nil {
		return x.Lt
	}
	return ""
}

func (x *RangeQuery) GetLte() string {
	if x != nil {
		return x.Lte
	}
	return ""
}

// MatchAllQuery matches every document. Useful as the base of a query
// that only filters, and for browsing a type by sort order.
type MatchAllQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchAllQuery) Reset() {
	*x = MatchAllQuery{}
	mi := &file_distribution_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchAllQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchAllQuery) ProtoMessage() {}

func (x *MatchAllQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchAllQuery.ProtoReflect.Descriptor instead.
func (*MatchAllQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{4}
}

// TermQuery matches an exact, unanalysed value. Use it for keyword,
// boolean, date and numeric fields; a term query against a text field
// matches individual analysed tokens, which is rarely what you want.
type TermQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to match against.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Value that the field must have.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Boost multiplies the score contribution of the clause. Defaults to 1.
	Boost         float64 `protobuf:"fixed64,3,opt,name=boost,proto3" json:"boost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermQuery) Reset() {
	*x = TermQuery{}
	mi := &file_distribution_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermQuery) ProtoMessage() {}

func (x *TermQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermQuery.ProtoReflect.Descriptor instead.
func (*TermQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{5}
}

func (x *TermQuery) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TermQuery) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TermQuery) GetBoost() float64 {
	if x != nil {
		return x.Boost
	}
	return 0
}

// TermsQuery matches documents where the field has any of the values.
type TermsQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to match against.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Values, any one of which is a match.
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	// Boost multiplies the score contribution of the clause. Defaults to 1.
	Boost         float64 `protobuf:"fixed64,3,opt,name=boost,proto3" json:"boost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermsQuery) Reset() {
	*x = TermsQuery{}
	mi := &file_distribution_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsQuery) ProtoMessage() {}

func (x *TermsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsQuery.ProtoReflect.Descriptor instead.
func (*TermsQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{6}
}

func (x *TermsQuery) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TermsQuery) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *TermsQuery) GetBoost() float64 {
	if x != nil {
		return x.Boost
	}
	return 0
}

// MatchQuery matches analysed text: the value is run through the
// analyser of the field, and a document matches if any of the resulting
// terms do.
type MatchQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to match against.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Value to match.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Boost multiplies the score contribution of the clause. Defaults to 1.
	Boost         float64 `protobuf:"fixed64,3,opt,name=boost,proto3" json:"boost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchQuery) Reset() {
	*x = MatchQuery{}
	mi := &file_distribution_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQuery) ProtoMessage() {}

func (x *MatchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQuery.ProtoReflect.Descriptor instead.
func (*MatchQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{7}
}

func (x *MatchQuery) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *MatchQuery) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MatchQuery) GetBoost() float64 {
	if x != nil {
		return x.Boost
	}
	return 0
}

// MatchPhraseQuery matches analysed text where the terms occur in the
// given order, next to each other.
type MatchPhraseQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to match against.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Value to match as a phrase.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPhraseQuery) Reset() {
	*x = MatchPhraseQuery{}
	mi := &file_distribution_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPhraseQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPhraseQuery) ProtoMessage() {}

func (x *MatchPhraseQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPhraseQuery.ProtoReflect.Descriptor instead.
func (*MatchPhraseQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{8}
}

func (x *MatchPhraseQuery) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *MatchPhraseQuery) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// PrefixQuery matches values that start with the given value. Run it
// against a keyword field, or against a field that the mappings report as
// "prefix": those are analysed for prefix matching and are much cheaper to
// search as you type.
type PrefixQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to match against.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Value that the field must start with.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// CaseInsensitive matches regardless of case.
	CaseInsensitive bool `protobuf:"varint,3,opt,name=case_insensitive,json=caseInsensitive,proto3" json:"case_insensitive,omitempty"`
	// Boost multiplies the score contribution of the clause. Defaults to 1.
	Boost         float64 `protobuf:"fixed64,4,opt,name=boost,proto3" json:"boost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixQuery) Reset() {
	*x = PrefixQuery{}
	mi := &file_distribution_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixQuery) ProtoMessage() {}

func (x *PrefixQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixQuery.ProtoReflect.Descriptor instead.
func (*PrefixQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{9}
}

func (x *PrefixQuery) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *PrefixQuery) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PrefixQuery) GetCaseInsensitive() bool {
	if x != nil {
		return x.CaseInsensitive
	}
	return false
}

func (x *PrefixQuery) GetBoost() float64 {
	if x != nil {
		return x.Boost
	}
	return 0
}

// MultiMatchQuery matches analysed text against several fields at once.
type MultiMatchQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields to match against. A field can carry a boost as a "^"-suffix,
	// e.g. "document.title^3".
	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// Type is the multi-match query type. Valid values are best_fields,
	// most_fields, cross_fields, phrase, phrase_prefix and bool_prefix.
	// Defaults to best_fields.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Query text to match.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// Boost multiplies the score contribution of the clause. Defaults to 1.
	Boost float64 `protobuf:"fixed64,4,opt,name=boost,proto3" json:"boost,omitempty"`
	// BooleanAnd requires all terms of the query to match.
	BooleanAnd bool `protobuf:"varint,5,opt,name=boolean_and,json=booleanAnd,proto3" json:"boolean_and,omitempty"`
	// MinimumShouldMatch is the number of query terms that must match when
	// the terms are combined with "or". Takes the full minimum-should-match
	// expression syntax, e.g. "2" or "75%".
	MinimumShouldMatch string `protobuf:"bytes,6,opt,name=minimum_should_match,json=minimumShouldMatch,proto3" json:"minimum_should_match,omitempty"`
	// TieBreaker is how much the score of matches in other fields than the
	// best-scoring one contributes, between 0 and 1. Defaults to 0, i.e.
	// only the best field counts.
	TieBreaker float32 `protobuf:"fixed32,7,opt,name=tie_breaker,json=tieBreaker,proto3" json:"tie_breaker,omitempty"`
	// PrefixLength is the number of leading characters that fuzzy matching
	// leaves unchanged. Defaults to 0.
	PrefixLength int64 `protobuf:"varint,8,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	// Fuzziness is the edit distance allowed when matching terms. Absent
	// means exact term matching.
	Fuzziness     *Fuzziness `protobuf:"bytes,9,opt,name=fuzziness,proto3" json:"fuzziness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiMatchQuery) Reset() {
	*x = MultiMatchQuery{}
	mi := &file_distribution_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiMatchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiMatchQuery) ProtoMessage() {}

func (x *MultiMatchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiMatchQuery.ProtoReflect.Descriptor instead.
func (*MultiMatchQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{10}
}

func (x *MultiMatchQuery) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *MultiMatchQuery) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MultiMatchQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MultiMatchQuery) GetBoost() float64 {
	if x != nil {
		return x.Boost
	}
	return 0
}

func (x *MultiMatchQuery) GetBooleanAnd() bool {
	if x != nil {
		return x.BooleanAnd
	}
	return false
}

func (x *MultiMatchQuery) GetMinimumShouldMatch() string {
	if x != nil {
		return x.MinimumShouldMatch
	}
	return ""
}

func (x *MultiMatchQuery) GetTieBreaker() float32 {
	if x != nil {
		return x.TieBreaker
	}
	return 0
}

func (x *MultiMatchQuery) GetPrefixLength() int64 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *MultiMatchQuery) GetFuzziness() *Fuzziness {
	if x != nil {
		return x.Fuzziness
	}
	return nil
}

// Fuzziness is the edit distance allowed when matching terms.
type Fuzziness struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Edits is the maximum allowed Levenshtein edit distance. Valid values
	// are 0, 1 and 2.
	Edits int64 `protobuf:"varint,1,opt,name=edits,proto3" json:"edits,omitempty"`
	// Auto derives the allowed edit distance from the length of the term.
	// Takes precedence over edits when set.
	Auto          *FuzzinessAuto `protobuf:"bytes,2,opt,name=auto,proto3" json:"auto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fuzziness) Reset() {
	*x = Fuzziness{}
	mi := &file_distribution_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fuzziness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fuzziness) ProtoMessage() {}

func (x *Fuzziness) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fuzziness.ProtoReflect.Descriptor instead.
func (*Fuzziness) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{11}
}

func (x *Fuzziness) GetEdits() int64 {
	if x != nil {
		return x.Edits
	}
	return 0
}

func (x *Fuzziness) GetAuto() *FuzzinessAuto {
	if x != nil {
		return x.Auto
	}
	return nil
}

// FuzzinessAuto configures automatic fuzziness thresholds. The low and
// high values are the term length boundaries for the edit distance tiers:
//
//   - Terms shorter than low characters must match exactly (0 edits).
//   - Terms of low to high-1 characters allow at most 1 edit.
//   - Terms of high characters or more allow at most 2 edits.
//
// Both zero uses the default thresholds, 3 and 6.
type FuzzinessAuto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Low is the term length where 1 edit starts being allowed.
	Low int64 `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	// High is the term length where 2 edits start being allowed.
	High          int64 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuzzinessAuto) Reset() {
	*x = FuzzinessAuto{}
	mi := &file_distribution_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuzzinessAuto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuzzinessAuto) ProtoMessage() {}

func (x *FuzzinessAuto) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuzzinessAuto.ProtoReflect.Descriptor instead.
func (*FuzzinessAuto) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{12}
}

func (x *FuzzinessAuto) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *FuzzinessAuto) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

// KnnQuery is a semantic query: it looks up the documents whose
// embeddings are closest to a query vector, rather than the documents that
// contain the query terms.
//
// The clause has two independent choices, and the server validates both -
// the fields are plain fields rather than oneofs so that the combinations
// can be relaxed later without renumbering, but an invalid combination is
// rejected as an invalid argument, it is never guessed at.
//
//  1. Where the query vector comes from: exactly one of text and vector.
//  2. How many neighbours come back: exactly one of k and min_similarity.
//
// Similarity is cosine similarity throughout, in the range [-1, 1], where
// higher means closer and 1 means identical direction. The embeddings are
// normalized, so this is the same dial as maximum inner product; the
// server converts from OpenSearch's own score space so that both
// min_similarity and the per-hit scores are stated as cosine similarity.
// Hit.score for a knn hit is therefore directly comparable to
// min_similarity, which is how a threshold is found: run a k query, look
// at where the results stop being relevant, and read the threshold off the
// scores.
//
// Thresholds are model-dependent and are not portable between deployments
// or across an embedding model upgrade. Treat a min_similarity value as
// something to recalibrate, not as a constant.
type KnnQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text to search for, embedded server-side with the current embedding
	// model. This is the normal way to run a semantic query, and the only
	// one that survives a model upgrade unchanged, since the server
	// re-embeds the text with whatever model is current.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Vector to search for, as a raw embedding. Advanced use: the caller has
	// to produce it with the same model and dimension as the index, and a
	// model upgrade invalidates it. Prefer text unless the vector comes from
	// somewhere the server cannot re-derive it from. A vector of the wrong
	// dimension is an invalid argument.
	Vector []float32 `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	// K is the number of nearest neighbours to retrieve. The hits come back
	// ordered by similarity, and there are always k of them (fewer only when
	// the filtered candidate set is smaller), no matter how poor the last
	// ones are - a k query has no relevance floor. Mutually exclusive with
	// min_similarity, and one of the two must be set.
	K int64 `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
	// MinSimilarity turns the clause into a radial query: every document at
	// or above this cosine similarity is a hit, however many that turns out
	// to be, up to size. Use it when "everything that is at least this
	// close" is the question - it makes a result set that does not silently
	// pad itself with weak matches the way a fixed k does, and it is the
	// same predicate that subscriptions match on, so a query is how a
	// subscription threshold is previewed.
	//
	// Cosine similarity in [-1, 1]; higher is closer. Mutually exclusive
	// with k, and one of the two must be set. The field is optional so that
	// a floor of 0 - every document that isn't pointing away from the query
	// - can be asked for, and is distinct from not asking for a radial
	// query at all.
	MinSimilarity *float32 `protobuf:"fixed32,4,opt,name=min_similarity,json=minSimilarity,proto3,oneof" json:"min_similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnnQuery) Reset() {
	*x = KnnQuery{}
	mi := &file_distribution_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnnQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnnQuery) ProtoMessage() {}

func (x *KnnQuery) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnnQuery.ProtoReflect.Descriptor instead.
func (*KnnQuery) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{13}
}

func (x *KnnQuery) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *KnnQuery) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *KnnQuery) GetK() int64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *KnnQuery) GetMinSimilarity() float32 {
	if x != nil && x.MinSimilarity != nil {
		return *x.MinSimilarity
	}
	return 0
}

// Sort sorts the hits on a field. Sort on keyword, date, boolean or
// numeric fields; text fields aren't sortable.
type Sort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to sort on.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Desc sorts in descending order instead of ascending.
	Desc          bool `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_distribution_search_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{14}
}

func (x *Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sort) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of documents that matched the query, which can be more
	// than the number of returned hits.
	Total *HitsTotal `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	// Hits in the requested order, at most size of them.
	Hits          []*Hit `protobuf:"bytes,2,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_distribution_search_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{15}
}

func (x *QueryResponse) GetTotal() *HitsTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *QueryResponse) GetHits() []*Hit {
	if x != nil {
		return x.Hits
	}
	return nil
}

// HitsTotal is the number of matching documents. The count is exact up to
// a server-side limit, above which it is reported as a lower bound.
type HitsTotal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value is the number of matching documents, interpreted according to
	// relation.
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// Relation is "eq" when value is the exact number of matches, and "gte"
	// when the matches were only counted up to value.
	Relation      string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitsTotal) Reset() {
	*x = HitsTotal{}
	mi := &file_distribution_search_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitsTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitsTotal) ProtoMessage() {}

func (x *HitsTotal) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitsTotal.ProtoReflect.Descriptor instead.
func (*HitsTotal) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{16}
}

func (x *HitsTotal) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *HitsTotal) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type Hit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the UUID of the document. Pass it to Content.GetDocument to
	// fetch the document itself, or ask the query for it with
	// load_documents.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Score is the relevance score of the hit. Only meaningful for hits
	// ordered by relevance; a sorted query leaves it at zero.
	//
	// For a knn query the score is the cosine similarity of the document to
	// the query vector, in [-1, 1] and on the same scale as
	// KnnQuery.min_similarity: the server converts it out of OpenSearch's
	// score space so that the two can be compared directly. For a text query
	// it is an unbounded BM25 score, comparable between hits of the same
	// query and meaningless between queries.
	Score float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	// Fields are the values of the requested fields, keyed by field name.
	// Fields without a value for the document are absent.
	Fields map[string]*StringValues `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Document is the loaded document, when the query asked for it with
	// load_documents and the document is still stored. It is the current
	// stored version rather than the version the index holds: a document
	// that has been corrected since it was indexed is delivered as it stands
	// now, and the fields of the hit are what it was matched on.
	Document *newsdoc.Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	// Subset is what the document type's extractors collected from the
	// delivered document, when the query named the type in subset.
	Subset []*ExtractedValues `protobuf:"bytes,5,rep,name=subset,proto3" json:"subset,omitempty"`
	// Version is the stored version the loaded document or subset was taken
	// from, and zero when neither was requested or the document was no
	// longer there to load.
	Version       int64 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hit) Reset() {
	*x = Hit{}
	mi := &file_distribution_search_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{17}
}

func (x *Hit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Hit) GetFields() map[string]*StringValues {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Hit) GetDocument() *newsdoc.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *Hit) GetSubset() []*ExtractedValues {
	if x != nil {
		return x.Subset
	}
	return nil
}

func (x *Hit) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// StringValues is the value of a flat index field. All field values are
// carried as strings regardless of the type of the field; dates are RFC
// 3339. A field is always a list because flattening a document collapses
// repeated blocks into parallel lists - values of the same block instance
// can't be paired up across fields.
type StringValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Values of the field, in index order.
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValues) Reset() {
	*x = StringValues{}
	mi := &file_distribution_search_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValues) ProtoMessage() {}

func (x *StringValues) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValues.ProtoReflect.Descriptor instead.
func (*StringValues) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{18}
}

func (x *StringValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetMappingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DocumentType to get the mappings of. Required.
	DocumentType  string `protobuf:"bytes,1,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMappingsRequest) Reset() {
	*x = GetMappingsRequest{}
	mi := &file_distribution_search_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMappingsRequest) ProtoMessage() {}

func (x *GetMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMappingsRequest.ProtoReflect.Descriptor instead.
func (*GetMappingsRequest) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{19}
}

func (x *GetMappingsRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

type GetMappingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Properties of the document type, sorted by name.
	Properties    []*MappingProperty `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMappingsResponse) Reset() {
	*x = GetMappingsResponse{}
	mi := &file_distribution_search_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMappingsResponse) ProtoMessage() {}

func (x *GetMappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMappingsResponse.ProtoReflect.Descriptor instead.
func (*GetMappingsResponse) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{20}
}

func (x *GetMappingsResponse) GetProperties() []*MappingProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

// MappingProperty is a searchable field of a document type.
type MappingProperty struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the property, as used in queries.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the property: "text", "keyword", "date", "long", "double",
	// "boolean", or "alias" for a property that is another name for the
	// property named by path.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Path is the property that an alias property points to. Empty for
	// everything but aliases.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Fields are alternative indexings of the property, queried as
	// "name.field". A text property commonly has a "keyword" field for
	// exact matching and sorting, and a "prefix" field for as-you-type
	// matching.
	Fields        []*MappingField `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingProperty) Reset() {
	*x = MappingProperty{}
	mi := &file_distribution_search_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingProperty) ProtoMessage() {}

func (x *MappingProperty) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingProperty.ProtoReflect.Descriptor instead.
func (*MappingProperty) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{21}
}

func (x *MappingProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MappingProperty) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MappingProperty) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MappingProperty) GetFields() []*MappingField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// MappingField is an alternative indexing of a property.
type MappingField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the field, appended to the property name with a dot to query
	// it.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the field, from the same vocabulary as the property type,
	// plus "prefix" for fields analysed for prefix matching.
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingField) Reset() {
	*x = MappingField{}
	mi := &file_distribution_search_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingField) ProtoMessage() {}

func (x *MappingField) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_search_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingField.ProtoReflect.Descriptor instead.
func (*MappingField) Descriptor() ([]byte, []int) {
	return file_distribution_search_proto_rawDescGZIP(), []int{22}
}

func (x *MappingField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MappingField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_distribution_search_proto protoreflect.FileDescriptor

var file_distribution_search_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x65, 0x6c, 0x65,
	0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x15, 0x6e, 0x65, 0x77, 0x73, 0x64, 0x6f, 0x63, 0x2f, 0x6e, 0x65, 0x77, 0x73,
	0x64, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x06, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x69, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x32, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x31, 0x0a, 0x03, 0x6b, 0x6e, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4b, 0x6e, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x03, 0x6b, 0x6e, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x2f, 0x0a, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x6c, 0x65,
	0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6c,
	0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x47, 0x0a, 0x06,
	0x73, 0x75, 0x62, 0x73, 0x65, 0x74, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73,
	0x75, 0x62, 0x73, 0x65, 0x74, 0x12, 0x3a, 0x0a, 0x19, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x69,
	0x6e, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x53, 0x0a, 0x0a, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x72, 0x65, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x11, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x59, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x65, 0x74, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x69, 0x0a, 0x0f, 0x52, 0x65, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x40, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x91, 0x05, 0x0a, 0x05,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x36, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6c,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x39, 0x0a,
	0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48,
	0x00, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x12, 0x43, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x6c, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x08, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x12, 0x36, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65,
	0x72, 0x6d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12,
	0x39, 0x0a, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x48, 0x00, 0x52, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x12, 0x39, 0x0a, 0x05, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65, 0x6c, 0x65, 0x70,
	0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x05,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x4c, 0x0a, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x70,
	0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x65, 0x6c,
	0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x68, 0x72,
	0x61, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x3c, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68,
	0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x49, 0x0a, 0x0b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x6c,
	0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x42, 0x0c, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x94, 0x02, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x30, 0x0a,
	0x04, 0x6d, 0x75, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x6c,
	0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x04, 0x6d, 0x75, 0x73, 0x74, 0x12,
	0x37, 0x0a, 0x08, 0x6d, 0x75, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x07, 0x6d, 0x75, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x68, 0x6f, 0x75,
	0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68,
	0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x12, 0x34,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f,
	0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x12, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x53, 0x68, 0x6f, 0x75, 0x6c,
	0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x66, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x67, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x67, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x22, 0x0f,
	0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x4d, 0x0a, 0x09, 0x54, 0x65, 0x72, 0x6d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x22, 0x50,
	0x0a, 0x0a, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f,
	0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x73, 0x74,
	0x22, 0x4e, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f,
	0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x73, 0x74,
	0x22, 0x3e, 0x0a, 0x10, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x7a, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63,
	0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x63, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x22, 0xc2, 0x02, 0x0a,
	0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x6f, 0x6c,
	0x65, 0x61, 0x6e, 0x5f, 0x61, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x62,
	0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x41, 0x6e, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x69, 0x6e,
	0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x73, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x69, 0x65, 0x5f, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x74, 0x69, 0x65, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x3e, 0x0a, 0x09, 0x66, 0x75, 0x7a, 0x7a, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x7a,
	0x7a, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x09, 0x66, 0x75, 0x7a, 0x7a, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x22, 0x5b, 0x0a, 0x09, 0x46, 0x75, 0x7a, 0x7a, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x64, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65,
	0x64, 0x69, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x75, 0x7a, 0x7a, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x04, 0x61, 0x75, 0x74, 0x6f, 0x22, 0x35,
	0x0a, 0x0d, 0x46, 0x75, 0x7a, 0x7a, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6c, 0x6f,
	0x77, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x22, 0x83, 0x01, 0x0a, 0x08, 0x4b, 0x6e, 0x6e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c,
	0x0a, 0x01, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6b, 0x12, 0x2a, 0x0a, 0x0e,
	0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x69, 0x6e, 0x53, 0x69, 0x6d, 0x69, 0x6c,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6d, 0x69, 0x6e,
	0x5f, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x22, 0x30, 0x0a, 0x04, 0x53,
	0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x77, 0x0a,
	0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x69, 0x74, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x68, 0x69, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x69, 0x74,
	0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x22, 0x3d, 0x0a, 0x09, 0x48, 0x69, 0x74, 0x73, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd4, 0x02, 0x0a, 0x03, 0x48, 0x69, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x69, 0x74, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x64, 0x6f, 0x63, 0x2e,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x06, 0x73, 0x75, 0x62, 0x73,
	0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x5e, 0x0a, 0x0b,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x39, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x26, 0x0a, 0x0c,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x5d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x6c, 0x65,
	0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x8a,
	0x01, 0x0a, 0x0f, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x3b,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x36, 0x0a, 0x0c, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x32, 0xc2, 0x01, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x52,
	0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61,
	0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x64, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x29, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x74, 0x61, 0x62, 0x2f, 0x65, 0x6c, 0x65, 0x70,
	0x68, 0x61, 0x6e, 0x74, 0x2d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_distribution_search_proto_rawDescOnce sync.Once
	file_distribution_search_proto_rawDescData = file_distribution_search_proto_rawDesc
)

func file_distribution_search_proto_rawDescGZIP() []byte {
	file_distribution_search_proto_rawDescOnce.Do(func() {
		file_distribution_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_distribution_search_proto_rawDescData)
	})
	return file_distribution_search_proto_rawDescData
}

var file_distribution_search_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_distribution_search_proto_goTypes = []any{
	(*QueryRequest)(nil),        // 0: elephant.distribution.QueryRequest
	(*Query)(nil),               // 1: elephant.distribution.Query
	(*BoolQuery)(nil),           // 2: elephant.distribution.BoolQuery
	(*RangeQuery)(nil),          // 3: elephant.distribution.RangeQuery
	(*MatchAllQuery)(nil),       // 4: elephant.distribution.MatchAllQuery
	(*TermQuery)(nil),           // 5: elephant.distribution.TermQuery
	(*TermsQuery)(nil),          // 6: elephant.distribution.TermsQuery
	(*MatchQuery)(nil),          // 7: elephant.distribution.MatchQuery
	(*MatchPhraseQuery)(nil),    // 8: elephant.distribution.MatchPhraseQuery
	(*PrefixQuery)(nil),         // 9: elephant.distribution.PrefixQuery
	(*MultiMatchQuery)(nil),     // 10: elephant.distribution.MultiMatchQuery
	(*Fuzziness)(nil),           // 11: elephant.distribution.Fuzziness
	(*FuzzinessAuto)(nil),       // 12: elephant.distribution.FuzzinessAuto
	(*KnnQuery)(nil),            // 13: elephant.distribution.KnnQuery
	(*Sort)(nil),                // 14: elephant.distribution.Sort
	(*QueryResponse)(nil),       // 15: elephant.distribution.QueryResponse
	(*HitsTotal)(nil),           // 16: elephant.distribution.HitsTotal
	(*Hit)(nil),                 // 17: elephant.distribution.Hit
	(*StringValues)(nil),        // 18: elephant.distribution.StringValues
	(*GetMappingsRequest)(nil),  // 19: elephant.distribution.GetMappingsRequest
	(*GetMappingsResponse)(nil), // 20: elephant.distribution.GetMappingsResponse
	(*MappingProperty)(nil),     // 21: elephant.distribution.MappingProperty
	(*MappingField)(nil),        // 22: elephant.distribution.MappingField
	nil,                         // 23: elephant.distribution.QueryRequest.SubsetEntry
	nil,                         // 24: elephant.distribution.QueryRequest.RenditionsEntry
	nil,                         // 25: elephant.distribution.Hit.FieldsEntry
	(*newsdoc.Document)(nil),    // 26: newsdoc.Document
	(*ExtractedValues)(nil),     // 27: elephant.distribution.ExtractedValues
	(*Subsets)(nil),             // 28: elephant.distribution.Subsets
	(*RenditionParameters)(nil), // 29: elephant.distribution.RenditionParameters
}
var file_distribution_search_proto_depIdxs = []int32{
	1,  // 0: elephant.distribution.QueryRequest.query:type_name -> elephant.distribution.Query
	13, // 1: elephant.distribution.QueryRequest.knn:type_name -> elephant.distribution.KnnQuery
	14, // 2: elephant.distribution.QueryRequest.sort:type_name -> elephant.distribution.Sort
	23, // 3: elephant.distribution.QueryRequest.subset:type_name -> elephant.distribution.QueryRequest.SubsetEntry
	24, // 4: elephant.distribution.QueryRequest.renditions:type_name -> elephant.distribution.QueryRequest.RenditionsEntry
	2,  // 5: elephant.distribution.Query.bool:type_name -> elephant.distribution.BoolQuery
	3,  // 6: elephant.distribution.Query.range:type_name -> elephant.distribution.RangeQuery
	4,  // 7: elephant.distribution.Query.match_all:type_name -> elephant.distribution.MatchAllQuery
	5,  // 8: elephant.distribution.Query.term:type_name -> elephant.distribution.TermQuery
	6,  // 9: elephant.distribution.Query.terms:type_name -> elephant.distribution.TermsQuery
	7,  // 10: elephant.distribution.Query.match:type_name -> elephant.distribution.MatchQuery
	8,  // 11: elephant.distribution.Query.match_phrase:type_name -> elephant.distribution.MatchPhraseQuery
	9,  // 12: elephant.distribution.Query.prefix:type_name -> elephant.distribution.PrefixQuery
	10, // 13: elephant.distribution.Query.multi_match:type_name -> elephant.distribution.MultiMatchQuery
	1,  // 14: elephant.distribution.BoolQuery.must:type_name -> elephant.distribution.Query
	1,  // 15: elephant.distribution.BoolQuery.must_not:type_name -> elephant.distribution.Query
	1,  // 16: elephant.distribution.BoolQuery.should:type_name -> elephant.distribution.Query
	1,  // 17: elephant.distribution.BoolQuery.filter:type_name -> elephant.distribution.Query
	11, // 18: elephant.distribution.MultiMatchQuery.fuzziness:type_name -> elephant.distribution.Fuzziness
	12, // 19: elephant.distribution.Fuzziness.auto:type_name -> elephant.distribution.FuzzinessAuto
	16, // 20: elephant.distribution.QueryResponse.total:type_name -> elephant.distribution.HitsTotal
	17, // 21: elephant.distribution.QueryResponse.hits:type_name -> elephant.distribution.Hit
	25, // 22: elephant.distribution.Hit.fields:type_name -> elephant.distribution.Hit.FieldsEntry
	26, // 23: elephant.distribution.Hit.document:type_name -> newsdoc.Document
	27, // 24: elephant.distribution.Hit.subset:type_name -> elephant.distribution.ExtractedValues
	21, // 25: elephant.distribution.GetMappingsResponse.properties:type_name -> elephant.distribution.MappingProperty
	22, // 26: elephant.distribution.MappingProperty.fields:type_name -> elephant.distribution.MappingField
	28, // 27: elephant.distribution.QueryRequest.SubsetEntry.value:type_name -> elephant.distribution.Subsets
	29, // 28: elephant.distribution.QueryRequest.RenditionsEntry.value:type_name -> elephant.distribution.RenditionParameters
	18, // 29: elephant.distribution.Hit.FieldsEntry.value:type_name -> elephant.distribution.StringValues
	0,  // 30: elephant.distribution.Search.Query:input_type -> elephant.distribution.QueryRequest
	19, // 31: elephant.distribution.Search.GetMappings:input_type -> elephant.distribution.GetMappingsRequest
	15, // 32: elephant.distribution.Search.Query:output_type -> elephant.distribution.QueryResponse
	20, // 33: elephant.distribution.Search.GetMappings:output_type -> elephant.distribution.GetMappingsResponse
	32, // [32:34] is the sub-list for method output_type
	30, // [30:32] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_distribution_search_proto_init() }
func file_distribution_search_proto_init() {
	if File_distribution_search_proto != nil {
		return
	}
	file_distribution_service_proto_init()
	file_distribution_search_proto_msgTypes[1].OneofWrappers = []any{
		(*Query_Bool)(nil),
		(*Query_Range)(nil),
		(*Query_Exists)(nil),
		(*Query_MatchAll)(nil),
		(*Query_Term)(nil),
		(*Query_Terms)(nil),
		(*Query_Match)(nil),
		(*Query_MatchPhrase)(nil),
		(*Query_QueryString)(nil),
		(*Query_Prefix)(nil),
		(*Query_MultiMatch)(nil),
	}
	file_distribution_search_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_distribution_search_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distribution_search_proto_goTypes,
		DependencyIndexes: file_distribution_search_proto_depIdxs,
		MessageInfos:      file_distribution_search_proto_msgTypes,
	}.Build()
	File_distribution_search_proto = out.File
	file_distribution_search_proto_rawDesc = nil
	file_distribution_search_proto_goTypes = nil
	file_distribution_search_proto_depIdxs = nil
}
