// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: distribution/search.proto

package distribution

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ================
// Search Interface
// ================

// Search exposes the distribution search index: a query surface over the
// documents that Content delivers, with the same visibility rules. It is
// read-only.
//
// Access requires the "dist_search" scope, which is granted by "dist_read"
// (search is a view of what the caller can already fetch) and by
// "dist_admin".
type Search interface {
	// Query searches one language series of one tier. Language is required
	// and a query never fans out across languages: searching several
	// languages is several calls.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)

	// GetMappings returns the searchable fields of a document type and the
	// type of each field, as the union across the language indexes. Use it
	// to find out what can be queried, and how, before building a query.
	GetMappings(context.Context, *GetMappingsRequest) (*GetMappingsResponse, error)
}

// ======================
// Search Protobuf Client
// ======================

type searchProtobufClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewSearchProtobufClient creates a Protobuf client that implements the Search interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewSearchProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Search {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "elephant.distribution", "Search")
	urls := [2]string{
		serviceURL + "Query",
		serviceURL + "GetMappings",
	}

	return &searchProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *searchProtobufClient) Query(ctx context.Context, in *QueryRequest) (*QueryResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "elephant.distribution")
	ctx = ctxsetters.WithServiceName(ctx, "Search")
	ctx = ctxsetters.WithMethodName(ctx, "Query")
	caller := c.callQuery
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*QueryRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*QueryRequest) when calling interceptor")
					}
					return c.callQuery(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*QueryResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*QueryResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *searchProtobufClient) callQuery(ctx context.Context, in *QueryRequest) (*QueryResponse, error) {
	out := new(QueryResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *searchProtobufClient) GetMappings(ctx context.Context, in *GetMappingsRequest) (*GetMappingsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "elephant.distribution")
	ctx = ctxsetters.WithServiceName(ctx, "Search")
	ctx = ctxsetters.WithMethodName(ctx, "GetMappings")
	caller := c.callGetMappings
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetMappingsRequest) (*GetMappingsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetMappingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetMappingsRequest) when calling interceptor")
					}
					return c.callGetMappings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetMappingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetMappingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *searchProtobufClient) callGetMappings(ctx context.Context, in *GetMappingsRequest) (*GetMappingsResponse, error) {
	out := new(GetMappingsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==================
// Search JSON Client
// ==================

type searchJSONClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewSearchJSONClient creates a JSON client that implements the Search interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewSearchJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Search {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "elephant.distribution", "Search")
	urls := [2]string{
		serviceURL + "Query",
		serviceURL + "GetMappings",
	}

	return &searchJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *searchJSONClient) Query(ctx context.Context, in *QueryRequest) (*QueryResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "elephant.distribution")
	ctx = ctxsetters.WithServiceName(ctx, "Search")
	ctx = ctxsetters.WithMethodName(ctx, "Query")
	caller := c.callQuery
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*QueryRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*QueryRequest) when calling interceptor")
					}
					return c.callQuery(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*QueryResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*QueryResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *searchJSONClient) callQuery(ctx context.Context, in *QueryRequest) (*QueryResponse, error) {
	out := new(QueryResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *searchJSONClient) GetMappings(ctx context.Context, in *GetMappingsRequest) (*GetMappingsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "elephant.distribution")
	ctx = ctxsetters.WithServiceName(ctx, "Search")
	ctx = ctxsetters.WithMethodName(ctx, "GetMappings")
	caller := c.callGetMappings
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetMappingsRequest) (*GetMappingsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetMappingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetMappingsRequest) when calling interceptor")
					}
					return c.callGetMappings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetMappingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetMappingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *searchJSONClient) callGetMappings(ctx context.Context, in *GetMappingsRequest) (*GetMappingsResponse, error) {
	out := new(GetMappingsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =====================
// Search Server Handler
// =====================

type searchServer struct {
	Search
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewSearchServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewSearchServer(svc Search, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &searchServer{
		Search:           svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *searchServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *searchServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// SearchPathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const SearchPathPrefix = "/twirp/elephant.distribution.Search/"

func (s *searchServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "elephant.distribution")
	ctx = ctxsetters.WithServiceName(ctx, "Search")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "elephant.distribution.Search" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "Query":
		s.serveQuery(ctx, resp, req)
		return
	case "GetMappings":
		s.serveGetMappings(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *searchServer) serveQuery(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveQueryJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveQueryProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *searchServer) serveQueryJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Query")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(QueryRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Search.Query
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*QueryRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*QueryRequest) when calling interceptor")
					}
					return s.Search.Query(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*QueryResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*QueryResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *QueryResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *QueryResponse and nil error while calling Query. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *searchServer) serveQueryProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Query")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(QueryRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Search.Query
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*QueryRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*QueryRequest) when calling interceptor")
					}
					return s.Search.Query(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*QueryResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*QueryResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *QueryResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *QueryResponse and nil error while calling Query. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *searchServer) serveGetMappings(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetMappingsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetMappingsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *searchServer) serveGetMappingsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetMappings")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetMappingsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Search.GetMappings
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetMappingsRequest) (*GetMappingsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetMappingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetMappingsRequest) when calling interceptor")
					}
					return s.Search.GetMappings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetMappingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetMappingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetMappingsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetMappingsResponse and nil error while calling GetMappings. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *searchServer) serveGetMappingsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetMappings")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetMappingsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Search.GetMappings
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetMappingsRequest) (*GetMappingsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetMappingsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetMappingsRequest) when calling interceptor")
					}
					return s.Search.GetMappings(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetMappingsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetMappingsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetMappingsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetMappingsResponse and nil error while calling GetMappings. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *searchServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *searchServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *searchServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "elephant.distribution", "Search")
}

var twirpFileDescriptor1 = []byte{
	// 1687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0x1b, 0xc7,
	0x15, 0xf6, 0xf2, 0x4f, 0xdc, 0xb3, 0xa4, 0x64, 0x4f, 0x9d, 0x64, 0xcb, 0x14, 0x89, 0xb2, 0x72,
	0x1d, 0xc5, 0x80, 0x29, 0x57, 0x49, 0xdd, 0x38, 0x6d, 0x8d, 0x5a, 0x6d, 0x1c, 0x05, 0x8d, 0x03,
	0x75, 0x68, 0x14, 0x68, 0x8b, 0x76, 0xb1, 0xe4, 0x0e, 0xc9, 0x81, 0xf6, 0x87, 0x99, 0x99, 0xb5,
	0x2d, 0xdf, 0xf6, 0xa6, 0xe8, 0x5d, 0x81, 0x3e, 0x46, 0x9f, 0x22, 0x6f, 0xd2, 0x37, 0x29, 0xe6,
	0xcc, 0xec, 0x72, 0xa9, 0x68, 0x69, 0x19, 0xe8, 0x15, 0x67, 0xbe, 0xf9, 0xce, 0x99, 0x33, 0x3f,
	0xe7, 0xcc, 0xb7, 0x84, 0x1f, 0xc7, 0x5c, 0x2a, 0xc1, 0xa7, 0x85, 0xe2, 0x79, 0x76, 0x24, 0x59,
	0x24, 0x66, 0xcb, 0xf1, 0x4a, 0xe4, 0x2a, 0x27, 0xef, 0xb0, 0x84, 0xad, 0x96, 0x51, 0xa6, 0xc6,
	0x75, 0xce, 0xe8, 0x9d, 0x8c, 0xbd, 0x94, 0x71, 0x3e, 0x3b, 0xb2, 0xbf, 0x86, 0x3d, 0x1a, 0x5d,
	0x72, 0x24, 0x5e, 0xf0, 0x19, 0x33, 0x63, 0xc1, 0x7f, 0x76, 0x60, 0xf0, 0x87, 0x82, 0x89, 0x0b,
	0xca, 0xbe, 0x2b, 0x98, 0x54, 0x64, 0x04, 0xfd, 0x24, 0xca, 0x16, 0x45, 0xb4, 0x60, 0xbe, 0xb3,
	0xef, 0x1c, 0xba, 0xb4, 0xea, 0x13, 0x02, 0x1d, 0xc5, 0x99, 0xf0, 0x5b, 0x88, 0x63, 0x9b, 0xfc,
	0x14, 0x76, 0xe3, 0x7c, 0x56, 0xa4, 0x2c, 0x53, 0xa1, 0xba, 0x58, 0x31, 0xe9, 0xb7, 0xf7, 0xdb,
	0x87, 0x2e, 0x1d, 0x96, 0xe8, 0x73, 0x0d, 0x92, 0x63, 0xe8, 0x7e, 0xa7, 0xa7, 0xf1, 0x3b, 0xfb,
	0xce, 0xa1, 0x77, 0xfc, 0x93, 0xf1, 0x95, 0x2b, 0x18, 0x9b, 0x50, 0x0c, 0x95, 0xfc, 0x0c, 0xda,
	0xe7, 0x59, 0xe6, 0xbb, 0x68, 0xf1, 0x61, 0x83, 0xc5, 0xef, 0xb3, 0xcc, 0x18, 0x69, 0xae, 0x8e,
	0x50, 0xf2, 0xd7, 0xcc, 0xef, 0xee, 0x3b, 0x87, 0x6d, 0x8a, 0x6d, 0x8d, 0xcd, 0x45, 0x9e, 0xfa,
	0x3d, 0x83, 0xe9, 0x36, 0x39, 0x82, 0x8e, 0xcc, 0x85, 0xf2, 0x77, 0xf6, 0xdb, 0x87, 0xde, 0xf1,
	0xfb, 0x0d, 0xbe, 0x27, 0xb9, 0x50, 0x14, 0x89, 0xe4, 0x5d, 0xe8, 0xcd, 0x39, 0x4b, 0x62, 0xe9,
	0xf7, 0x71, 0x79, 0xb6, 0x47, 0x3e, 0x00, 0x58, 0xb0, 0x8c, 0x89, 0x48, 0x1b, 0xf8, 0x80, 0x1b,
	0x53, 0x43, 0xf4, 0xf6, 0x24, 0x79, 0x14, 0x87, 0xe5, 0x6e, 0x48, 0xdf, 0xdb, 0x77, 0x0e, 0xfb,
	0x74, 0xa8, 0xd1, 0xdf, 0x95, 0x20, 0xf9, 0x0a, 0x7a, 0xb2, 0x98, 0x4a, 0xa6, 0xfc, 0x01, 0x46,
	0x74, 0xb4, 0x75, 0x7f, 0xcc, 0x51, 0x8d, 0x27, 0x68, 0xf1, 0x65, 0xa6, 0xc4, 0x05, 0xb5, 0xe6,
	0xe4, 0x0b, 0xbc, 0x36, 0xd1, 0x34, 0x61, 0xa1, 0x60, 0x59, 0xcc, 0xb5, 0x55, 0x28, 0xf9, 0x22,
	0xe3, 0xd9, 0xc2, 0x1f, 0xe2, 0xd4, 0xef, 0x59, 0x02, 0x2d, 0xc7, 0x27, 0x66, 0x98, 0x4c, 0x00,
	0x2a, 0x1b, 0xe9, 0xef, 0x62, 0x20, 0x9f, 0x5e, 0x27, 0x90, 0xca, 0x93, 0x34, 0xc1, 0xd4, 0xdc,
	0x90, 0xfb, 0x40, 0x7e, 0x10, 0x90, 0xf4, 0xf7, 0x30, 0x92, 0x5b, 0x97, 0x23, 0x91, 0xe4, 0x7d,
	0x70, 0xe3, 0x48, 0xb1, 0x10, 0x4f, 0xec, 0xa6, 0xb9, 0x7f, 0x1a, 0x78, 0xaa, 0x4f, 0xed, 0x3d,
	0xd8, 0xc1, 0x41, 0x95, 0xfb, 0xb7, 0x70, 0xa8, 0xa7, 0xbb, 0xcf, 0x73, 0xf2, 0x11, 0x0c, 0x78,
	0x36, 0x4b, 0x8a, 0x98, 0x85, 0x4b, 0x95, 0x26, 0x3e, 0x41, 0xf7, 0x9e, 0xc5, 0x4e, 0x55, 0x9a,
	0x8c, 0xfe, 0x04, 0x5e, 0x6d, 0xbf, 0xc8, 0x4d, 0x68, 0x9f, 0xb3, 0x0b, 0x7b, 0xc3, 0x75, 0x93,
	0x7c, 0x06, 0xdd, 0x17, 0x51, 0x52, 0x30, 0xbc, 0xdd, 0xde, 0xf1, 0x07, 0x4d, 0x77, 0x02, 0x9d,
	0x48, 0x6a, 0xc8, 0x5f, 0xb4, 0x3e, 0x77, 0x46, 0x1c, 0xf6, 0x2e, 0xed, 0xc0, 0x15, 0xee, 0x7f,
	0xb3, 0xe9, 0xfe, 0x5e, 0x83, 0xfb, 0xca, 0xd1, 0x59, 0x24, 0xa2, 0x94, 0x29, 0x26, 0xea, 0x53,
	0x05, 0xff, 0xea, 0x42, 0x17, 0xb7, 0x9e, 0x3c, 0x84, 0xce, 0x34, 0xcf, 0x13, 0x9c, 0xc2, 0x3b,
	0xde, 0x6f, 0x70, 0x77, 0x92, 0xe7, 0x09, 0xf2, 0x4f, 0x6f, 0x50, 0xe4, 0x93, 0x47, 0xd0, 0x15,
	0x51, 0xb6, 0x28, 0xe3, 0xf8, 0xa8, 0x29, 0x0e, 0xcd, 0x29, 0x2d, 0x8d, 0x05, 0xf1, 0xa1, 0xc7,
	0x5e, 0x71, 0xa9, 0x74, 0x8a, 0x3b, 0x87, 0xee, 0xe9, 0x0d, 0x6a, 0xfb, 0xe4, 0xb7, 0xe0, 0xa6,
	0x91, 0x9a, 0x2d, 0xc3, 0x28, 0x49, 0x6c, 0x86, 0xdf, 0x69, 0x70, 0xfc, 0x4c, 0xf3, 0x9e, 0x24,
	0x55, 0x54, 0xfd, 0xd4, 0x02, 0x7a, 0x45, 0x8a, 0x89, 0x14, 0x73, 0xb7, 0x79, 0x45, 0xcf, 0x99,
	0x48, 0xab, 0x15, 0x69, 0xbe, 0x5e, 0x91, 0xfe, 0x95, 0x98, 0xe0, 0xcd, 0x2b, 0xd2, 0x86, 0xb2,
	0x5a, 0x11, 0x5a, 0x68, 0x53, 0x9c, 0xde, 0xdf, 0xd9, 0x6a, 0x8a, 0x31, 0x57, 0xa6, 0x68, 0x41,
	0xbe, 0x81, 0x81, 0x59, 0xf2, 0x6a, 0x29, 0x22, 0xc9, 0xfc, 0x3e, 0x7a, 0xf8, 0x78, 0x9b, 0x87,
	0x33, 0x64, 0x96, 0x7e, 0xbc, 0x74, 0x8d, 0x91, 0x03, 0x18, 0x60, 0xcd, 0x0b, 0xb5, 0x4d, 0xb6,
	0xc0, 0x9a, 0xa7, 0x37, 0xd8, 0x43, 0x74, 0x82, 0x20, 0xf9, 0x15, 0xf4, 0x56, 0x82, 0xcd, 0xf9,
	0x2b, 0xac, 0x33, 0xde, 0x71, 0xd0, 0x30, 0xd9, 0x19, 0x92, 0xca, 0x79, 0xac, 0x0d, 0xf9, 0x1a,
	0xbc, 0xb4, 0x48, 0x14, 0x0f, 0xcd, 0x8a, 0x3d, 0x74, 0x71, 0xb7, 0x29, 0x5e, 0xcd, 0xdc, 0x58,
	0x36, 0xa4, 0x15, 0x74, 0x32, 0x00, 0x98, 0xe5, 0xe5, 0x85, 0x0f, 0xfe, 0xdd, 0x02, 0xb7, 0xba,
	0x67, 0xe4, 0x01, 0x74, 0xd2, 0x42, 0x2a, 0xdf, 0xc1, 0xf2, 0xb1, 0xbd, 0xce, 0x23, 0x93, 0xfc,
	0x02, 0xfa, 0xfa, 0x37, 0xcc, 0x72, 0xe5, 0xb7, 0xae, 0x61, 0xb5, 0xa3, 0xd9, 0xdf, 0xe6, 0x8a,
	0x7c, 0x06, 0x3d, 0xb9, 0xcc, 0x8b, 0x24, 0xc6, 0x27, 0xe7, 0x4d, 0x66, 0x96, 0xab, 0xad, 0xe6,
	0x3c, 0x51, 0x4c, 0xf8, 0x9d, 0xeb, 0x58, 0x19, 0x2e, 0x79, 0x00, 0xb7, 0x53, 0x9e, 0xf1, 0xb4,
	0x48, 0x43, 0xe3, 0xc7, 0x6e, 0xa3, 0x79, 0x68, 0x88, 0x1d, 0x9b, 0xe0, 0x10, 0x6e, 0x52, 0x30,
	0x07, 0x58, 0x27, 0x11, 0xb9, 0x0d, 0x5d, 0x7c, 0x31, 0x6c, 0x49, 0x30, 0x1d, 0xb2, 0x0b, 0xad,
	0x85, 0xb2, 0xcf, 0x69, 0x6b, 0xa1, 0x74, 0xd9, 0x58, 0x28, 0x66, 0xd2, 0x8b, 0xea, 0xa6, 0x66,
	0x24, 0x0a, 0x53, 0xca, 0xa5, 0xad, 0x04, 0x19, 0x89, 0x32, 0xef, 0x9b, 0x4b, 0x75, 0x33, 0xd8,
	0x83, 0xe1, 0x46, 0x4e, 0x05, 0xcf, 0xc0, 0xad, 0x92, 0xa4, 0x61, 0xde, 0xdb, 0xf5, 0x62, 0xe4,
	0xda, 0x02, 0xa3, 0xd1, 0x69, 0x9e, 0x4b, 0x85, 0xf3, 0x3b, 0xd4, 0x74, 0x82, 0x33, 0x80, 0x75,
	0xea, 0x34, 0xf8, 0x7b, 0x17, 0x7a, 0xe8, 0x42, 0xe2, 0x01, 0xba, 0xd4, 0xf6, 0x1a, 0x3c, 0x7e,
	0x0b, 0xb0, 0xbe, 0x5a, 0xff, 0x87, 0x08, 0x1f, 0xc3, 0xcd, 0xcb, 0xf9, 0xf5, 0x36, 0x5e, 0x83,
	0xd7, 0xe0, 0xd5, 0x52, 0xe6, 0xad, 0x02, 0xfa, 0x04, 0x6e, 0xce, 0x22, 0xc9, 0x42, 0x9e, 0x49,
	0x96, 0x49, 0xae, 0xf8, 0x0b, 0x73, 0x7a, 0x7d, 0xba, 0xa7, 0xf1, 0xaf, 0xd7, 0xf0, 0x3a, 0xf6,
	0x4e, 0x3d, 0xf6, 0xef, 0x5b, 0xb0, 0x77, 0x29, 0xd9, 0x6a, 0x5a, 0xc3, 0xd9, 0xd0, 0x1a, 0x5a,
	0x7e, 0x5d, 0xac, 0x58, 0x25, 0xbf, 0x2e, 0x56, 0xe8, 0xd5, 0xe8, 0x2a, 0x73, 0x67, 0xac, 0x72,
	0xba, 0x72, 0x2e, 0xf2, 0x21, 0x78, 0xfa, 0x09, 0x60, 0x51, 0x16, 0x46, 0x59, 0x8c, 0x77, 0xa8,
	0x4f, 0xc1, 0x42, 0x4f, 0xb2, 0xb8, 0xf1, 0x92, 0xf7, 0xd0, 0xf7, 0x15, 0x97, 0x5c, 0xbb, 0x54,
	0x9c, 0x85, 0x53, 0xc1, 0xa2, 0x73, 0x26, 0xb0, 0x8c, 0xb6, 0x28, 0x28, 0xce, 0x4e, 0x0c, 0x42,
	0x0e, 0x60, 0x68, 0xea, 0x4f, 0x98, 0xb0, 0x6c, 0xa1, 0x96, 0x58, 0x27, 0xdb, 0x74, 0x60, 0xc0,
	0x6f, 0x10, 0x23, 0x8f, 0xc1, 0x9d, 0x17, 0xaf, 0x5f, 0xf3, 0x8c, 0x49, 0x69, 0xe5, 0x5e, 0x53,
	0xf9, 0x7f, 0x5a, 0xf2, 0xe8, 0xda, 0x24, 0xf8, 0x0b, 0xb8, 0x15, 0xae, 0xd7, 0xce, 0x62, 0xae,
	0x24, 0x1e, 0x5f, 0x9b, 0x9a, 0x0e, 0xf9, 0x1c, 0x3a, 0x51, 0xa1, 0x72, 0xfb, 0xea, 0xdd, 0x79,
	0x93, 0xf7, 0x27, 0x85, 0xca, 0x29, 0x5a, 0x04, 0x3f, 0x87, 0xe1, 0x06, 0x8c, 0x29, 0x98, 0xbf,
	0xb4, 0xee, 0x75, 0x53, 0x1f, 0xcc, 0x92, 0x2f, 0x96, 0xe8, 0xbc, 0x4d, 0xb1, 0x1d, 0xfc, 0xdd,
	0x81, 0x7e, 0xa9, 0x4d, 0xf1, 0xe4, 0xd8, 0x2b, 0x65, 0x6f, 0x14, 0xb6, 0x31, 0x67, 0xd8, 0x4c,
	0xe5, 0x02, 0x73, 0xa6, 0x45, 0x6d, 0x8f, 0x0c, 0xc0, 0x39, 0xc7, 0xd3, 0x6c, 0x53, 0xe7, 0x9c,
	0xdc, 0x83, 0xdd, 0x94, 0x6b, 0x05, 0x97, 0xf2, 0x24, 0x12, 0x5c, 0x19, 0x01, 0xdd, 0x3a, 0xbd,
	0x41, 0x87, 0x29, 0xcf, 0x26, 0x15, 0xfc, 0x0f, 0xc7, 0x39, 0xb9, 0x05, 0x7b, 0xe1, 0x26, 0x39,
	0x78, 0x00, 0x1d, 0x2d, 0x62, 0x1b, 0xee, 0x34, 0x81, 0x4e, 0xcc, 0xe4, 0x0c, 0xe3, 0xee, 0x53,
	0x6c, 0x07, 0x2f, 0x61, 0x68, 0xb5, 0x9d, 0x5c, 0xe5, 0x99, 0x64, 0xe4, 0x21, 0x74, 0x55, 0xae,
	0xa2, 0x37, 0x29, 0x8d, 0x53, 0xae, 0xe4, 0x73, 0xcd, 0xa3, 0x86, 0x4e, 0xc6, 0x7a, 0x53, 0x94,
	0xb4, 0x25, 0x7d, 0xd4, 0x6c, 0x46, 0x91, 0x17, 0xfc, 0x1a, 0xdc, 0xca, 0xc7, 0x3a, 0xdb, 0xec,
	0x21, 0x9a, 0x6c, 0x1b, 0x41, 0x5f, 0xb0, 0xc4, 0x48, 0x6d, 0x93, 0x04, 0x55, 0x3f, 0xf8, 0x6f,
	0x1b, 0xda, 0xa7, 0x5c, 0xe9, 0x82, 0xc9, 0xcb, 0x65, 0xb6, 0x38, 0xe6, 0xad, 0x9c, 0xe5, 0xc2,
	0x64, 0x4d, 0x8b, 0x9a, 0x0e, 0x79, 0x5c, 0xa5, 0x98, 0x79, 0x3a, 0xee, 0x36, 0x87, 0x37, 0x7e,
	0x8a, 0x44, 0x2b, 0xb3, 0x6d, 0x2a, 0xde, 0x87, 0x7e, 0xa9, 0xe8, 0xad, 0xde, 0xb9, 0x35, 0x2e,
	0x3f, 0xba, 0x4a, 0x55, 0x4f, 0x2b, 0x8a, 0x9e, 0xce, 0xca, 0xfb, 0xee, 0xd6, 0xe9, 0xbe, 0x7c,
	0xa5, 0x44, 0x34, 0x53, 0x2c, 0xfe, 0x23, 0xd6, 0xcf, 0x4a, 0xd5, 0xfb, 0xb0, 0xf3, 0x82, 0x09,
	0xa9, 0xd7, 0x6d, 0xbe, 0x62, 0xca, 0xae, 0x56, 0xbe, 0xab, 0x62, 0x9a, 0x70, 0xb9, 0x64, 0x71,
	0x18, 0x29, 0xcc, 0x40, 0x97, 0x7a, 0x15, 0xf6, 0x44, 0x91, 0x8f, 0x61, 0x6f, 0xce, 0x85, 0x54,
	0x61, 0x05, 0x62, 0x12, 0xba, 0x74, 0x17, 0xe1, 0xb3, 0x12, 0xd5, 0xdb, 0x1b, 0xb3, 0x39, 0x13,
	0x82, 0xc5, 0x98, 0x85, 0x7d, 0x5a, 0xf5, 0x75, 0x1e, 0x6b, 0xf9, 0xce, 0x04, 0x8b, 0x8d, 0xc4,
	0x36, 0x9f, 0x3a, 0x83, 0x12, 0x44, 0x8d, 0xfd, 0x37, 0xf0, 0x6a, 0x9b, 0x75, 0x85, 0x08, 0x7e,
	0xb4, 0x29, 0x82, 0x0f, 0x9a, 0x34, 0x36, 0xea, 0x1d, 0xbb, 0x07, 0x35, 0xf5, 0x7b, 0x17, 0x06,
	0xf5, 0xa1, 0xda, 0xb3, 0xe3, 0xd4, 0x9f, 0x9d, 0xe0, 0x11, 0x90, 0xaf, 0x98, 0x7a, 0x16, 0xad,
	0x56, 0x3c, 0x5b, 0xc8, 0xf2, 0xcb, 0xf6, 0x00, 0x86, 0x1b, 0x5f, 0xaa, 0x36, 0xb0, 0x41, 0xfd,
	0x43, 0x35, 0xf8, 0x2b, 0xfc, 0x68, 0xc3, 0xd4, 0x26, 0xc1, 0x53, 0x80, 0x95, 0xc8, 0x57, 0x4c,
	0x28, 0x6e, 0x67, 0xdb, 0xa2, 0x9d, 0x8c, 0xf1, 0x99, 0xe1, 0x5f, 0xd0, 0x9a, 0x65, 0xf0, 0x4f,
	0x07, 0xf6, 0x2e, 0x8d, 0xeb, 0x2c, 0xcc, 0xa2, 0xb4, 0x0c, 0x07, 0xdb, 0x57, 0x96, 0x7a, 0x02,
	0x9d, 0x55, 0xa4, 0x96, 0xb6, 0xd2, 0x63, 0x9b, 0xfc, 0xb2, 0xba, 0xc7, 0x46, 0xcc, 0x1c, 0x6c,
	0x8f, 0x09, 0x4f, 0xa7, 0xbc, 0xc4, 0xc1, 0x43, 0x18, 0xd4, 0xf1, 0xeb, 0x06, 0x72, 0xfc, 0xbd,
	0x03, 0xbd, 0x09, 0xfe, 0x1d, 0x41, 0x68, 0xf9, 0x39, 0x72, 0x70, 0x8d, 0xef, 0xc4, 0xd1, 0x9d,
	0xed, 0x24, 0xbb, 0xd7, 0x31, 0x78, 0xb5, 0x23, 0x20, 0x9f, 0x34, 0x18, 0xfd, 0xf0, 0x84, 0x47,
	0xf7, 0xae, 0x43, 0x35, 0xb3, 0x9c, 0x1c, 0xff, 0xf9, 0xc1, 0x82, 0xab, 0x65, 0x31, 0x1d, 0xcf,
	0xf2, 0xf4, 0x48, 0xa9, 0x68, 0x7a, 0x54, 0x1a, 0xdf, 0xc7, 0x44, 0x99, 0xdd, 0x8f, 0x56, 0xfc,
	0xa8, 0xee, 0x67, 0xda, 0xc3, 0xff, 0x4c, 0x3e, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38,
	0x5e, 0xa8, 0x64, 0x9a, 0x11, 0x00, 0x00,
}
