// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: distribution/delivery.proto

package distributionconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	distribution "github.com/ttab/elephant-public-api/distribution"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeliveryName is the fully-qualified name of the Delivery service.
	DeliveryName = "elephant.distribution.Delivery"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeliveryCreateDestinationProcedure is the fully-qualified name of the Delivery's
	// CreateDestination RPC.
	DeliveryCreateDestinationProcedure = "/elephant.distribution.Delivery/CreateDestination"
	// DeliveryUpdateDestinationProcedure is the fully-qualified name of the Delivery's
	// UpdateDestination RPC.
	DeliveryUpdateDestinationProcedure = "/elephant.distribution.Delivery/UpdateDestination"
	// DeliveryGetDestinationProcedure is the fully-qualified name of the Delivery's GetDestination RPC.
	DeliveryGetDestinationProcedure = "/elephant.distribution.Delivery/GetDestination"
	// DeliveryListDestinationsProcedure is the fully-qualified name of the Delivery's ListDestinations
	// RPC.
	DeliveryListDestinationsProcedure = "/elephant.distribution.Delivery/ListDestinations"
	// DeliveryDeleteDestinationProcedure is the fully-qualified name of the Delivery's
	// DeleteDestination RPC.
	DeliveryDeleteDestinationProcedure = "/elephant.distribution.Delivery/DeleteDestination"
	// DeliverySetDestinationCredentialsProcedure is the fully-qualified name of the Delivery's
	// SetDestinationCredentials RPC.
	DeliverySetDestinationCredentialsProcedure = "/elephant.distribution.Delivery/SetDestinationCredentials"
	// DeliveryAttachSubscriptionProcedure is the fully-qualified name of the Delivery's
	// AttachSubscription RPC.
	DeliveryAttachSubscriptionProcedure = "/elephant.distribution.Delivery/AttachSubscription"
	// DeliveryDetachSubscriptionProcedure is the fully-qualified name of the Delivery's
	// DetachSubscription RPC.
	DeliveryDetachSubscriptionProcedure = "/elephant.distribution.Delivery/DetachSubscription"
	// DeliveryRewindSubscriptionProcedure is the fully-qualified name of the Delivery's
	// RewindSubscription RPC.
	DeliveryRewindSubscriptionProcedure = "/elephant.distribution.Delivery/RewindSubscription"
	// DeliveryGetCatchupStatusProcedure is the fully-qualified name of the Delivery's GetCatchupStatus
	// RPC.
	DeliveryGetCatchupStatusProcedure = "/elephant.distribution.Delivery/GetCatchupStatus"
	// DeliveryResumeDestinationProcedure is the fully-qualified name of the Delivery's
	// ResumeDestination RPC.
	DeliveryResumeDestinationProcedure = "/elephant.distribution.Delivery/ResumeDestination"
	// DeliverySuspendSubscriptionsProcedure is the fully-qualified name of the Delivery's
	// SuspendSubscriptions RPC.
	DeliverySuspendSubscriptionsProcedure = "/elephant.distribution.Delivery/SuspendSubscriptions"
	// DeliveryResumeSubscriptionsProcedure is the fully-qualified name of the Delivery's
	// ResumeSubscriptions RPC.
	DeliveryResumeSubscriptionsProcedure = "/elephant.distribution.Delivery/ResumeSubscriptions"
	// DeliverySkipDeliveryMatcherProcedure is the fully-qualified name of the Delivery's
	// SkipDeliveryMatcher RPC.
	DeliverySkipDeliveryMatcherProcedure = "/elephant.distribution.Delivery/SkipDeliveryMatcher"
	// DeliveryRotateDeliveryKeysProcedure is the fully-qualified name of the Delivery's
	// RotateDeliveryKeys RPC.
	DeliveryRotateDeliveryKeysProcedure = "/elephant.distribution.Delivery/RotateDeliveryKeys"
	// DeliveryListDeliveryOperationsProcedure is the fully-qualified name of the Delivery's
	// ListDeliveryOperations RPC.
	DeliveryListDeliveryOperationsProcedure = "/elephant.distribution.Delivery/ListDeliveryOperations"
)

// DeliveryClient is a client for the elephant.distribution.Delivery service.
type DeliveryClient interface {
	// CreateDestination registers a destination. It is created disabled
	// unless the request says otherwise, because a destination with no
	// credentials and no attached subscription is a destination being
	// configured rather than one that is broken.
	CreateDestination(context.Context, *connect.Request[distribution.CreateDestinationRequest]) (*connect.Response[distribution.CreateDestinationResponse], error)
	// UpdateDestination replaces the definition of a destination. The spec
	// is written whole: fields left out of it are cleared, not kept.
	// Credentials are not part of the spec and are not touched. Changing
	// the transport, format or name template restarts the destination's
	// worker, so an in-flight send completes and the next one uses the new
	// definition.
	UpdateDestination(context.Context, *connect.Request[distribution.UpdateDestinationRequest]) (*connect.Response[distribution.UpdateDestinationResponse], error)
	// GetDestination returns a destination as stored, with the status of
	// its credentials but never their values.
	GetDestination(context.Context, *connect.Request[distribution.GetDestinationRequest]) (*connect.Response[distribution.GetDestinationResponse], error)
	// ListDestinations lists the destinations the caller can see: the ones
	// owned by the organisation of the caller, and the ones owned by the
	// calling subject.
	ListDestinations(context.Context, *connect.Request[distribution.ListDestinationsRequest]) (*connect.Response[distribution.ListDestinationsResponse], error)
	// DeleteDestination marks a destination deleted and wipes its
	// credentials. It is not a row deletion: the inventory of what the
	// destination was given outlives it, because that is the record an
	// erasure request is answered from, and there is no way left to tell
	// the destination anything once the credentials are gone.
	//
	// For the same reason the deletion discharges the destination's
	// outstanding erasure obligations, recorded as "destination_deleted".
	// The inventory rows are kept as the record of what it was given.
	DeleteDestination(context.Context, *connect.Request[distribution.DeleteDestinationRequest]) (*connect.Response[distribution.DeleteDestinationResponse], error)
	// SetDestinationCredentials writes one kind of credential for a
	// destination, replacing whatever was there. There is no call that
	// reads them back.
	SetDestinationCredentials(context.Context, *connect.Request[distribution.SetDestinationCredentialsRequest]) (*connect.Response[distribution.SetDestinationCredentialsResponse], error)
	// AttachSubscription attaches a delivery subscription to a
	// destination. Both must have the same owner. The attachment records
	// the log position it was made at, and everything above that position
	// that the subscription matches is delivered - including the events
	// between the attachment and the matcher noticing it, which are
	// replayed.
	AttachSubscription(context.Context, *connect.Request[distribution.AttachSubscriptionRequest]) (*connect.Response[distribution.AttachSubscriptionResponse], error)
	// DetachSubscription removes an attachment. Queue rows already written
	// for the destination are still delivered: they are the destination's,
	// not the subscription's, which is also why a document the destination
	// has had keeps getting its corrections until the sticky window runs
	// out.
	DetachSubscription(context.Context, *connect.Request[distribution.DetachSubscriptionRequest]) (*connect.Response[distribution.DetachSubscriptionResponse], error)
	// RewindSubscription replays a subscription from an earlier log
	// position - "start me from Monday". It does not move the position the
	// subscription started at, which stays as the record of where the feed
	// began; it schedules a catch-up from the position given, which the
	// matcher runs paged and resumably alongside its ordinary work.
	//
	// Refused below the retention horizon, naming it: below that the
	// events and the extracted fields a rule would be evaluated against
	// are both gone, so there is nothing to replay. Refused across the
	// introduction of a field the rules reference, naming the boundary,
	// unless acknowledge_blind_window is set - below that boundary the
	// field is absent from every row and the rule reads as a no-match
	// rather than as a missing input.
	RewindSubscription(context.Context, *connect.Request[distribution.RewindSubscriptionRequest]) (*connect.Response[distribution.RewindSubscriptionResponse], error)
	// GetCatchupStatus reports how a subscription's running catch-up is
	// going: where it started, where it has got to, and - when the caller
	// acknowledged a blind window - the boundary they accepted and how
	// many events have actually been evaluated below it.
	//
	// The last number is why this call exists. Acknowledging a blind
	// window accepts a shortfall, and without a reader for it the
	// acknowledgement would be a one-way switch: accepted, and never
	// measured.
	GetCatchupStatus(context.Context, *connect.Request[distribution.GetCatchupStatusRequest]) (*connect.Response[distribution.GetCatchupStatusResponse], error)
	// ResumeDestination restarts a destination whose queue grew past its
	// depth or age limit and stopped. The operator chooses what happens to
	// what accumulated: deliver it, or skip up to a position. A skip
	// stamps the rows skipped rather than deleting them, so what was not
	// sent stays a query.
	//
	// Only a stalled destination can be resumed. On a running one a skip
	// would stamp rows the worker is in the middle of sending, so a resume
	// of a destination that is not stalled is refused with its state
	// named.
	//
	// A resume also rebaselines the queue limits at the current end of the
	// queue. Without that a drain cannot drain: the limit is checked
	// before the first send of a pass, so a destination that stopped
	// because its queue was too deep is still too deep the moment it
	// restarts, and would stop again without delivering anything. What
	// accumulated is delivered; the limits apply to what accumulates
	// after.
	ResumeDestination(context.Context, *connect.Request[distribution.ResumeDestinationRequest]) (*connect.Response[distribution.ResumeDestinationResponse], error)
	// SuspendSubscriptions stops delivery for an owner: every delivery
	// subscription they own or one of their subjects created stops
	// matching, and every destination they own stops sending. Rows already
	// queued hold rather than drain, so a resume can still deliver them.
	//
	// It is not expiry and it is not credential revocation. A suspended
	// owner's tokens carry whatever scopes the identity provider grants
	// them, and cutting those is done there.
	SuspendSubscriptions(context.Context, *connect.Request[distribution.SuspendSubscriptionsRequest]) (*connect.Response[distribution.SuspendSubscriptionsResponse], error)
	// ResumeSubscriptions lifts a suspension, from the position it was
	// suspended at or from the head of the log. Resuming at the head
	// leaves a gap, which is recorded rather than silent; resuming at the
	// prior position replays the window, subject to the same two refusals
	// RewindSubscription is subject to.
	ResumeSubscriptions(context.Context, *connect.Request[distribution.ResumeSubscriptionsRequest]) (*connect.Response[distribution.ResumeSubscriptionsResponse], error)
	// SkipDeliveryMatcher moves the delivery matcher's cursor forward,
	// deliberately, leaving a recorded gap in every delivery feed.
	//
	// It exists for one situation: the matcher has fallen below the
	// retention horizon, where the events it would read and the fields it
	// would evaluate have both been deleted, and it has halted rather than
	// deciding anything. The cursor cannot be moved by resuming a
	// destination - a destination resume stamps rows in one queue, and the
	// cursor is one row for the whole deployment - so this is its own
	// call, and it records who moved it, from where, to where, and why.
	//
	// Forward only. The skip is a request the matcher applies at the top
	// of its next pass; until then it is pending, which is visible.
	SkipDeliveryMatcher(context.Context, *connect.Request[distribution.SkipDeliveryMatcherRequest]) (*connect.Response[distribution.SkipDeliveryMatcherResponse], error)
	// RotateDeliveryKeys re-encrypts stored credentials under the current
	// keyring entry and reports how many rows still name an older one. A
	// retired key is safe to remove from the environment when that number
	// reaches zero.
	RotateDeliveryKeys(context.Context, *connect.Request[distribution.RotateDeliveryKeysRequest]) (*connect.Response[distribution.RotateDeliveryKeysResponse], error)
	// ListDeliveryOperations lists the deliberate operator decisions not to
	// deliver something: suspensions, resumes, destination skips, cursor
	// skips and rewinds. It is the answer to "why is there a hole in this
	// customer's feed", which is otherwise only in an incident note.
	ListDeliveryOperations(context.Context, *connect.Request[distribution.ListDeliveryOperationsRequest]) (*connect.Response[distribution.ListDeliveryOperationsResponse], error)
}

// NewDeliveryClient constructs a client for the elephant.distribution.Delivery service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeliveryClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeliveryClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deliveryMethods := distribution.File_distribution_delivery_proto.Services().ByName("Delivery").Methods()
	return &deliveryClient{
		createDestination: connect.NewClient[distribution.CreateDestinationRequest, distribution.CreateDestinationResponse](
			httpClient,
			baseURL+DeliveryCreateDestinationProcedure,
			connect.WithSchema(deliveryMethods.ByName("CreateDestination")),
			connect.WithClientOptions(opts...),
		),
		updateDestination: connect.NewClient[distribution.UpdateDestinationRequest, distribution.UpdateDestinationResponse](
			httpClient,
			baseURL+DeliveryUpdateDestinationProcedure,
			connect.WithSchema(deliveryMethods.ByName("UpdateDestination")),
			connect.WithClientOptions(opts...),
		),
		getDestination: connect.NewClient[distribution.GetDestinationRequest, distribution.GetDestinationResponse](
			httpClient,
			baseURL+DeliveryGetDestinationProcedure,
			connect.WithSchema(deliveryMethods.ByName("GetDestination")),
			connect.WithClientOptions(opts...),
		),
		listDestinations: connect.NewClient[distribution.ListDestinationsRequest, distribution.ListDestinationsResponse](
			httpClient,
			baseURL+DeliveryListDestinationsProcedure,
			connect.WithSchema(deliveryMethods.ByName("ListDestinations")),
			connect.WithClientOptions(opts...),
		),
		deleteDestination: connect.NewClient[distribution.DeleteDestinationRequest, distribution.DeleteDestinationResponse](
			httpClient,
			baseURL+DeliveryDeleteDestinationProcedure,
			connect.WithSchema(deliveryMethods.ByName("DeleteDestination")),
			connect.WithClientOptions(opts...),
		),
		setDestinationCredentials: connect.NewClient[distribution.SetDestinationCredentialsRequest, distribution.SetDestinationCredentialsResponse](
			httpClient,
			baseURL+DeliverySetDestinationCredentialsProcedure,
			connect.WithSchema(deliveryMethods.ByName("SetDestinationCredentials")),
			connect.WithClientOptions(opts...),
		),
		attachSubscription: connect.NewClient[distribution.AttachSubscriptionRequest, distribution.AttachSubscriptionResponse](
			httpClient,
			baseURL+DeliveryAttachSubscriptionProcedure,
			connect.WithSchema(deliveryMethods.ByName("AttachSubscription")),
			connect.WithClientOptions(opts...),
		),
		detachSubscription: connect.NewClient[distribution.DetachSubscriptionRequest, distribution.DetachSubscriptionResponse](
			httpClient,
			baseURL+DeliveryDetachSubscriptionProcedure,
			connect.WithSchema(deliveryMethods.ByName("DetachSubscription")),
			connect.WithClientOptions(opts...),
		),
		rewindSubscription: connect.NewClient[distribution.RewindSubscriptionRequest, distribution.RewindSubscriptionResponse](
			httpClient,
			baseURL+DeliveryRewindSubscriptionProcedure,
			connect.WithSchema(deliveryMethods.ByName("RewindSubscription")),
			connect.WithClientOptions(opts...),
		),
		getCatchupStatus: connect.NewClient[distribution.GetCatchupStatusRequest, distribution.GetCatchupStatusResponse](
			httpClient,
			baseURL+DeliveryGetCatchupStatusProcedure,
			connect.WithSchema(deliveryMethods.ByName("GetCatchupStatus")),
			connect.WithClientOptions(opts...),
		),
		resumeDestination: connect.NewClient[distribution.ResumeDestinationRequest, distribution.ResumeDestinationResponse](
			httpClient,
			baseURL+DeliveryResumeDestinationProcedure,
			connect.WithSchema(deliveryMethods.ByName("ResumeDestination")),
			connect.WithClientOptions(opts...),
		),
		suspendSubscriptions: connect.NewClient[distribution.SuspendSubscriptionsRequest, distribution.SuspendSubscriptionsResponse](
			httpClient,
			baseURL+DeliverySuspendSubscriptionsProcedure,
			connect.WithSchema(deliveryMethods.ByName("SuspendSubscriptions")),
			connect.WithClientOptions(opts...),
		),
		resumeSubscriptions: connect.NewClient[distribution.ResumeSubscriptionsRequest, distribution.ResumeSubscriptionsResponse](
			httpClient,
			baseURL+DeliveryResumeSubscriptionsProcedure,
			connect.WithSchema(deliveryMethods.ByName("ResumeSubscriptions")),
			connect.WithClientOptions(opts...),
		),
		skipDeliveryMatcher: connect.NewClient[distribution.SkipDeliveryMatcherRequest, distribution.SkipDeliveryMatcherResponse](
			httpClient,
			baseURL+DeliverySkipDeliveryMatcherProcedure,
			connect.WithSchema(deliveryMethods.ByName("SkipDeliveryMatcher")),
			connect.WithClientOptions(opts...),
		),
		rotateDeliveryKeys: connect.NewClient[distribution.RotateDeliveryKeysRequest, distribution.RotateDeliveryKeysResponse](
			httpClient,
			baseURL+DeliveryRotateDeliveryKeysProcedure,
			connect.WithSchema(deliveryMethods.ByName("RotateDeliveryKeys")),
			connect.WithClientOptions(opts...),
		),
		listDeliveryOperations: connect.NewClient[distribution.ListDeliveryOperationsRequest, distribution.ListDeliveryOperationsResponse](
			httpClient,
			baseURL+DeliveryListDeliveryOperationsProcedure,
			connect.WithSchema(deliveryMethods.ByName("ListDeliveryOperations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deliveryClient implements DeliveryClient.
type deliveryClient struct {
	createDestination         *connect.Client[distribution.CreateDestinationRequest, distribution.CreateDestinationResponse]
	updateDestination         *connect.Client[distribution.UpdateDestinationRequest, distribution.UpdateDestinationResponse]
	getDestination            *connect.Client[distribution.GetDestinationRequest, distribution.GetDestinationResponse]
	listDestinations          *connect.Client[distribution.ListDestinationsRequest, distribution.ListDestinationsResponse]
	deleteDestination         *connect.Client[distribution.DeleteDestinationRequest, distribution.DeleteDestinationResponse]
	setDestinationCredentials *connect.Client[distribution.SetDestinationCredentialsRequest, distribution.SetDestinationCredentialsResponse]
	attachSubscription        *connect.Client[distribution.AttachSubscriptionRequest, distribution.AttachSubscriptionResponse]
	detachSubscription        *connect.Client[distribution.DetachSubscriptionRequest, distribution.DetachSubscriptionResponse]
	rewindSubscription        *connect.Client[distribution.RewindSubscriptionRequest, distribution.RewindSubscriptionResponse]
	getCatchupStatus          *connect.Client[distribution.GetCatchupStatusRequest, distribution.GetCatchupStatusResponse]
	resumeDestination         *connect.Client[distribution.ResumeDestinationRequest, distribution.ResumeDestinationResponse]
	suspendSubscriptions      *connect.Client[distribution.SuspendSubscriptionsRequest, distribution.SuspendSubscriptionsResponse]
	resumeSubscriptions       *connect.Client[distribution.ResumeSubscriptionsRequest, distribution.ResumeSubscriptionsResponse]
	skipDeliveryMatcher       *connect.Client[distribution.SkipDeliveryMatcherRequest, distribution.SkipDeliveryMatcherResponse]
	rotateDeliveryKeys        *connect.Client[distribution.RotateDeliveryKeysRequest, distribution.RotateDeliveryKeysResponse]
	listDeliveryOperations    *connect.Client[distribution.ListDeliveryOperationsRequest, distribution.ListDeliveryOperationsResponse]
}

// CreateDestination calls elephant.distribution.Delivery.CreateDestination.
func (c *deliveryClient) CreateDestination(ctx context.Context, req *connect.Request[distribution.CreateDestinationRequest]) (*connect.Response[distribution.CreateDestinationResponse], error) {
	return c.createDestination.CallUnary(ctx, req)
}

// UpdateDestination calls elephant.distribution.Delivery.UpdateDestination.
func (c *deliveryClient) UpdateDestination(ctx context.Context, req *connect.Request[distribution.UpdateDestinationRequest]) (*connect.Response[distribution.UpdateDestinationResponse], error) {
	return c.updateDestination.CallUnary(ctx, req)
}

// GetDestination calls elephant.distribution.Delivery.GetDestination.
func (c *deliveryClient) GetDestination(ctx context.Context, req *connect.Request[distribution.GetDestinationRequest]) (*connect.Response[distribution.GetDestinationResponse], error) {
	return c.getDestination.CallUnary(ctx, req)
}

// ListDestinations calls elephant.distribution.Delivery.ListDestinations.
func (c *deliveryClient) ListDestinations(ctx context.Context, req *connect.Request[distribution.ListDestinationsRequest]) (*connect.Response[distribution.ListDestinationsResponse], error) {
	return c.listDestinations.CallUnary(ctx, req)
}

// DeleteDestination calls elephant.distribution.Delivery.DeleteDestination.
func (c *deliveryClient) DeleteDestination(ctx context.Context, req *connect.Request[distribution.DeleteDestinationRequest]) (*connect.Response[distribution.DeleteDestinationResponse], error) {
	return c.deleteDestination.CallUnary(ctx, req)
}

// SetDestinationCredentials calls elephant.distribution.Delivery.SetDestinationCredentials.
func (c *deliveryClient) SetDestinationCredentials(ctx context.Context, req *connect.Request[distribution.SetDestinationCredentialsRequest]) (*connect.Response[distribution.SetDestinationCredentialsResponse], error) {
	return c.setDestinationCredentials.CallUnary(ctx, req)
}

// AttachSubscription calls elephant.distribution.Delivery.AttachSubscription.
func (c *deliveryClient) AttachSubscription(ctx context.Context, req *connect.Request[distribution.AttachSubscriptionRequest]) (*connect.Response[distribution.AttachSubscriptionResponse], error) {
	return c.attachSubscription.CallUnary(ctx, req)
}

// DetachSubscription calls elephant.distribution.Delivery.DetachSubscription.
func (c *deliveryClient) DetachSubscription(ctx context.Context, req *connect.Request[distribution.DetachSubscriptionRequest]) (*connect.Response[distribution.DetachSubscriptionResponse], error) {
	return c.detachSubscription.CallUnary(ctx, req)
}

// RewindSubscription calls elephant.distribution.Delivery.RewindSubscription.
func (c *deliveryClient) RewindSubscription(ctx context.Context, req *connect.Request[distribution.RewindSubscriptionRequest]) (*connect.Response[distribution.RewindSubscriptionResponse], error) {
	return c.rewindSubscription.CallUnary(ctx, req)
}

// GetCatchupStatus calls elephant.distribution.Delivery.GetCatchupStatus.
func (c *deliveryClient) GetCatchupStatus(ctx context.Context, req *connect.Request[distribution.GetCatchupStatusRequest]) (*connect.Response[distribution.GetCatchupStatusResponse], error) {
	return c.getCatchupStatus.CallUnary(ctx, req)
}

// ResumeDestination calls elephant.distribution.Delivery.ResumeDestination.
func (c *deliveryClient) ResumeDestination(ctx context.Context, req *connect.Request[distribution.ResumeDestinationRequest]) (*connect.Response[distribution.ResumeDestinationResponse], error) {
	return c.resumeDestination.CallUnary(ctx, req)
}

// SuspendSubscriptions calls elephant.distribution.Delivery.SuspendSubscriptions.
func (c *deliveryClient) SuspendSubscriptions(ctx context.Context, req *connect.Request[distribution.SuspendSubscriptionsRequest]) (*connect.Response[distribution.SuspendSubscriptionsResponse], error) {
	return c.suspendSubscriptions.CallUnary(ctx, req)
}

// ResumeSubscriptions calls elephant.distribution.Delivery.ResumeSubscriptions.
func (c *deliveryClient) ResumeSubscriptions(ctx context.Context, req *connect.Request[distribution.ResumeSubscriptionsRequest]) (*connect.Response[distribution.ResumeSubscriptionsResponse], error) {
	return c.resumeSubscriptions.CallUnary(ctx, req)
}

// SkipDeliveryMatcher calls elephant.distribution.Delivery.SkipDeliveryMatcher.
func (c *deliveryClient) SkipDeliveryMatcher(ctx context.Context, req *connect.Request[distribution.SkipDeliveryMatcherRequest]) (*connect.Response[distribution.SkipDeliveryMatcherResponse], error) {
	return c.skipDeliveryMatcher.CallUnary(ctx, req)
}

// RotateDeliveryKeys calls elephant.distribution.Delivery.RotateDeliveryKeys.
func (c *deliveryClient) RotateDeliveryKeys(ctx context.Context, req *connect.Request[distribution.RotateDeliveryKeysRequest]) (*connect.Response[distribution.RotateDeliveryKeysResponse], error) {
	return c.rotateDeliveryKeys.CallUnary(ctx, req)
}

// ListDeliveryOperations calls elephant.distribution.Delivery.ListDeliveryOperations.
func (c *deliveryClient) ListDeliveryOperations(ctx context.Context, req *connect.Request[distribution.ListDeliveryOperationsRequest]) (*connect.Response[distribution.ListDeliveryOperationsResponse], error) {
	return c.listDeliveryOperations.CallUnary(ctx, req)
}

// DeliveryHandler is an implementation of the elephant.distribution.Delivery service.
type DeliveryHandler interface {
	// CreateDestination registers a destination. It is created disabled
	// unless the request says otherwise, because a destination with no
	// credentials and no attached subscription is a destination being
	// configured rather than one that is broken.
	CreateDestination(context.Context, *connect.Request[distribution.CreateDestinationRequest]) (*connect.Response[distribution.CreateDestinationResponse], error)
	// UpdateDestination replaces the definition of a destination. The spec
	// is written whole: fields left out of it are cleared, not kept.
	// Credentials are not part of the spec and are not touched. Changing
	// the transport, format or name template restarts the destination's
	// worker, so an in-flight send completes and the next one uses the new
	// definition.
	UpdateDestination(context.Context, *connect.Request[distribution.UpdateDestinationRequest]) (*connect.Response[distribution.UpdateDestinationResponse], error)
	// GetDestination returns a destination as stored, with the status of
	// its credentials but never their values.
	GetDestination(context.Context, *connect.Request[distribution.GetDestinationRequest]) (*connect.Response[distribution.GetDestinationResponse], error)
	// ListDestinations lists the destinations the caller can see: the ones
	// owned by the organisation of the caller, and the ones owned by the
	// calling subject.
	ListDestinations(context.Context, *connect.Request[distribution.ListDestinationsRequest]) (*connect.Response[distribution.ListDestinationsResponse], error)
	// DeleteDestination marks a destination deleted and wipes its
	// credentials. It is not a row deletion: the inventory of what the
	// destination was given outlives it, because that is the record an
	// erasure request is answered from, and there is no way left to tell
	// the destination anything once the credentials are gone.
	//
	// For the same reason the deletion discharges the destination's
	// outstanding erasure obligations, recorded as "destination_deleted".
	// The inventory rows are kept as the record of what it was given.
	DeleteDestination(context.Context, *connect.Request[distribution.DeleteDestinationRequest]) (*connect.Response[distribution.DeleteDestinationResponse], error)
	// SetDestinationCredentials writes one kind of credential for a
	// destination, replacing whatever was there. There is no call that
	// reads them back.
	SetDestinationCredentials(context.Context, *connect.Request[distribution.SetDestinationCredentialsRequest]) (*connect.Response[distribution.SetDestinationCredentialsResponse], error)
	// AttachSubscription attaches a delivery subscription to a
	// destination. Both must have the same owner. The attachment records
	// the log position it was made at, and everything above that position
	// that the subscription matches is delivered - including the events
	// between the attachment and the matcher noticing it, which are
	// replayed.
	AttachSubscription(context.Context, *connect.Request[distribution.AttachSubscriptionRequest]) (*connect.Response[distribution.AttachSubscriptionResponse], error)
	// DetachSubscription removes an attachment. Queue rows already written
	// for the destination are still delivered: they are the destination's,
	// not the subscription's, which is also why a document the destination
	// has had keeps getting its corrections until the sticky window runs
	// out.
	DetachSubscription(context.Context, *connect.Request[distribution.DetachSubscriptionRequest]) (*connect.Response[distribution.DetachSubscriptionResponse], error)
	// RewindSubscription replays a subscription from an earlier log
	// position - "start me from Monday". It does not move the position the
	// subscription started at, which stays as the record of where the feed
	// began; it schedules a catch-up from the position given, which the
	// matcher runs paged and resumably alongside its ordinary work.
	//
	// Refused below the retention horizon, naming it: below that the
	// events and the extracted fields a rule would be evaluated against
	// are both gone, so there is nothing to replay. Refused across the
	// introduction of a field the rules reference, naming the boundary,
	// unless acknowledge_blind_window is set - below that boundary the
	// field is absent from every row and the rule reads as a no-match
	// rather than as a missing input.
	RewindSubscription(context.Context, *connect.Request[distribution.RewindSubscriptionRequest]) (*connect.Response[distribution.RewindSubscriptionResponse], error)
	// GetCatchupStatus reports how a subscription's running catch-up is
	// going: where it started, where it has got to, and - when the caller
	// acknowledged a blind window - the boundary they accepted and how
	// many events have actually been evaluated below it.
	//
	// The last number is why this call exists. Acknowledging a blind
	// window accepts a shortfall, and without a reader for it the
	// acknowledgement would be a one-way switch: accepted, and never
	// measured.
	GetCatchupStatus(context.Context, *connect.Request[distribution.GetCatchupStatusRequest]) (*connect.Response[distribution.GetCatchupStatusResponse], error)
	// ResumeDestination restarts a destination whose queue grew past its
	// depth or age limit and stopped. The operator chooses what happens to
	// what accumulated: deliver it, or skip up to a position. A skip
	// stamps the rows skipped rather than deleting them, so what was not
	// sent stays a query.
	//
	// Only a stalled destination can be resumed. On a running one a skip
	// would stamp rows the worker is in the middle of sending, so a resume
	// of a destination that is not stalled is refused with its state
	// named.
	//
	// A resume also rebaselines the queue limits at the current end of the
	// queue. Without that a drain cannot drain: the limit is checked
	// before the first send of a pass, so a destination that stopped
	// because its queue was too deep is still too deep the moment it
	// restarts, and would stop again without delivering anything. What
	// accumulated is delivered; the limits apply to what accumulates
	// after.
	ResumeDestination(context.Context, *connect.Request[distribution.ResumeDestinationRequest]) (*connect.Response[distribution.ResumeDestinationResponse], error)
	// SuspendSubscriptions stops delivery for an owner: every delivery
	// subscription they own or one of their subjects created stops
	// matching, and every destination they own stops sending. Rows already
	// queued hold rather than drain, so a resume can still deliver them.
	//
	// It is not expiry and it is not credential revocation. A suspended
	// owner's tokens carry whatever scopes the identity provider grants
	// them, and cutting those is done there.
	SuspendSubscriptions(context.Context, *connect.Request[distribution.SuspendSubscriptionsRequest]) (*connect.Response[distribution.SuspendSubscriptionsResponse], error)
	// ResumeSubscriptions lifts a suspension, from the position it was
	// suspended at or from the head of the log. Resuming at the head
	// leaves a gap, which is recorded rather than silent; resuming at the
	// prior position replays the window, subject to the same two refusals
	// RewindSubscription is subject to.
	ResumeSubscriptions(context.Context, *connect.Request[distribution.ResumeSubscriptionsRequest]) (*connect.Response[distribution.ResumeSubscriptionsResponse], error)
	// SkipDeliveryMatcher moves the delivery matcher's cursor forward,
	// deliberately, leaving a recorded gap in every delivery feed.
	//
	// It exists for one situation: the matcher has fallen below the
	// retention horizon, where the events it would read and the fields it
	// would evaluate have both been deleted, and it has halted rather than
	// deciding anything. The cursor cannot be moved by resuming a
	// destination - a destination resume stamps rows in one queue, and the
	// cursor is one row for the whole deployment - so this is its own
	// call, and it records who moved it, from where, to where, and why.
	//
	// Forward only. The skip is a request the matcher applies at the top
	// of its next pass; until then it is pending, which is visible.
	SkipDeliveryMatcher(context.Context, *connect.Request[distribution.SkipDeliveryMatcherRequest]) (*connect.Response[distribution.SkipDeliveryMatcherResponse], error)
	// RotateDeliveryKeys re-encrypts stored credentials under the current
	// keyring entry and reports how many rows still name an older one. A
	// retired key is safe to remove from the environment when that number
	// reaches zero.
	RotateDeliveryKeys(context.Context, *connect.Request[distribution.RotateDeliveryKeysRequest]) (*connect.Response[distribution.RotateDeliveryKeysResponse], error)
	// ListDeliveryOperations lists the deliberate operator decisions not to
	// deliver something: suspensions, resumes, destination skips, cursor
	// skips and rewinds. It is the answer to "why is there a hole in this
	// customer's feed", which is otherwise only in an incident note.
	ListDeliveryOperations(context.Context, *connect.Request[distribution.ListDeliveryOperationsRequest]) (*connect.Response[distribution.ListDeliveryOperationsResponse], error)
}

// NewDeliveryHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeliveryHandler(svc DeliveryHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deliveryMethods := distribution.File_distribution_delivery_proto.Services().ByName("Delivery").Methods()
	deliveryCreateDestinationHandler := connect.NewUnaryHandler(
		DeliveryCreateDestinationProcedure,
		svc.CreateDestination,
		connect.WithSchema(deliveryMethods.ByName("CreateDestination")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryUpdateDestinationHandler := connect.NewUnaryHandler(
		DeliveryUpdateDestinationProcedure,
		svc.UpdateDestination,
		connect.WithSchema(deliveryMethods.ByName("UpdateDestination")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryGetDestinationHandler := connect.NewUnaryHandler(
		DeliveryGetDestinationProcedure,
		svc.GetDestination,
		connect.WithSchema(deliveryMethods.ByName("GetDestination")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryListDestinationsHandler := connect.NewUnaryHandler(
		DeliveryListDestinationsProcedure,
		svc.ListDestinations,
		connect.WithSchema(deliveryMethods.ByName("ListDestinations")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryDeleteDestinationHandler := connect.NewUnaryHandler(
		DeliveryDeleteDestinationProcedure,
		svc.DeleteDestination,
		connect.WithSchema(deliveryMethods.ByName("DeleteDestination")),
		connect.WithHandlerOptions(opts...),
	)
	deliverySetDestinationCredentialsHandler := connect.NewUnaryHandler(
		DeliverySetDestinationCredentialsProcedure,
		svc.SetDestinationCredentials,
		connect.WithSchema(deliveryMethods.ByName("SetDestinationCredentials")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryAttachSubscriptionHandler := connect.NewUnaryHandler(
		DeliveryAttachSubscriptionProcedure,
		svc.AttachSubscription,
		connect.WithSchema(deliveryMethods.ByName("AttachSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryDetachSubscriptionHandler := connect.NewUnaryHandler(
		DeliveryDetachSubscriptionProcedure,
		svc.DetachSubscription,
		connect.WithSchema(deliveryMethods.ByName("DetachSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryRewindSubscriptionHandler := connect.NewUnaryHandler(
		DeliveryRewindSubscriptionProcedure,
		svc.RewindSubscription,
		connect.WithSchema(deliveryMethods.ByName("RewindSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryGetCatchupStatusHandler := connect.NewUnaryHandler(
		DeliveryGetCatchupStatusProcedure,
		svc.GetCatchupStatus,
		connect.WithSchema(deliveryMethods.ByName("GetCatchupStatus")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryResumeDestinationHandler := connect.NewUnaryHandler(
		DeliveryResumeDestinationProcedure,
		svc.ResumeDestination,
		connect.WithSchema(deliveryMethods.ByName("ResumeDestination")),
		connect.WithHandlerOptions(opts...),
	)
	deliverySuspendSubscriptionsHandler := connect.NewUnaryHandler(
		DeliverySuspendSubscriptionsProcedure,
		svc.SuspendSubscriptions,
		connect.WithSchema(deliveryMethods.ByName("SuspendSubscriptions")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryResumeSubscriptionsHandler := connect.NewUnaryHandler(
		DeliveryResumeSubscriptionsProcedure,
		svc.ResumeSubscriptions,
		connect.WithSchema(deliveryMethods.ByName("ResumeSubscriptions")),
		connect.WithHandlerOptions(opts...),
	)
	deliverySkipDeliveryMatcherHandler := connect.NewUnaryHandler(
		DeliverySkipDeliveryMatcherProcedure,
		svc.SkipDeliveryMatcher,
		connect.WithSchema(deliveryMethods.ByName("SkipDeliveryMatcher")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryRotateDeliveryKeysHandler := connect.NewUnaryHandler(
		DeliveryRotateDeliveryKeysProcedure,
		svc.RotateDeliveryKeys,
		connect.WithSchema(deliveryMethods.ByName("RotateDeliveryKeys")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryListDeliveryOperationsHandler := connect.NewUnaryHandler(
		DeliveryListDeliveryOperationsProcedure,
		svc.ListDeliveryOperations,
		connect.WithSchema(deliveryMethods.ByName("ListDeliveryOperations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephant.distribution.Delivery/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeliveryCreateDestinationProcedure:
			deliveryCreateDestinationHandler.ServeHTTP(w, r)
		case DeliveryUpdateDestinationProcedure:
			deliveryUpdateDestinationHandler.ServeHTTP(w, r)
		case DeliveryGetDestinationProcedure:
			deliveryGetDestinationHandler.ServeHTTP(w, r)
		case DeliveryListDestinationsProcedure:
			deliveryListDestinationsHandler.ServeHTTP(w, r)
		case DeliveryDeleteDestinationProcedure:
			deliveryDeleteDestinationHandler.ServeHTTP(w, r)
		case DeliverySetDestinationCredentialsProcedure:
			deliverySetDestinationCredentialsHandler.ServeHTTP(w, r)
		case DeliveryAttachSubscriptionProcedure:
			deliveryAttachSubscriptionHandler.ServeHTTP(w, r)
		case DeliveryDetachSubscriptionProcedure:
			deliveryDetachSubscriptionHandler.ServeHTTP(w, r)
		case DeliveryRewindSubscriptionProcedure:
			deliveryRewindSubscriptionHandler.ServeHTTP(w, r)
		case DeliveryGetCatchupStatusProcedure:
			deliveryGetCatchupStatusHandler.ServeHTTP(w, r)
		case DeliveryResumeDestinationProcedure:
			deliveryResumeDestinationHandler.ServeHTTP(w, r)
		case DeliverySuspendSubscriptionsProcedure:
			deliverySuspendSubscriptionsHandler.ServeHTTP(w, r)
		case DeliveryResumeSubscriptionsProcedure:
			deliveryResumeSubscriptionsHandler.ServeHTTP(w, r)
		case DeliverySkipDeliveryMatcherProcedure:
			deliverySkipDeliveryMatcherHandler.ServeHTTP(w, r)
		case DeliveryRotateDeliveryKeysProcedure:
			deliveryRotateDeliveryKeysHandler.ServeHTTP(w, r)
		case DeliveryListDeliveryOperationsProcedure:
			deliveryListDeliveryOperationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeliveryHandler returns CodeUnimplemented from all methods.
type UnimplementedDeliveryHandler struct{}

func (UnimplementedDeliveryHandler) CreateDestination(context.Context, *connect.Request[distribution.CreateDestinationRequest]) (*connect.Response[distribution.CreateDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.CreateDestination is not implemented"))
}

func (UnimplementedDeliveryHandler) UpdateDestination(context.Context, *connect.Request[distribution.UpdateDestinationRequest]) (*connect.Response[distribution.UpdateDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.UpdateDestination is not implemented"))
}

func (UnimplementedDeliveryHandler) GetDestination(context.Context, *connect.Request[distribution.GetDestinationRequest]) (*connect.Response[distribution.GetDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.GetDestination is not implemented"))
}

func (UnimplementedDeliveryHandler) ListDestinations(context.Context, *connect.Request[distribution.ListDestinationsRequest]) (*connect.Response[distribution.ListDestinationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.ListDestinations is not implemented"))
}

func (UnimplementedDeliveryHandler) DeleteDestination(context.Context, *connect.Request[distribution.DeleteDestinationRequest]) (*connect.Response[distribution.DeleteDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.DeleteDestination is not implemented"))
}

func (UnimplementedDeliveryHandler) SetDestinationCredentials(context.Context, *connect.Request[distribution.SetDestinationCredentialsRequest]) (*connect.Response[distribution.SetDestinationCredentialsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.SetDestinationCredentials is not implemented"))
}

func (UnimplementedDeliveryHandler) AttachSubscription(context.Context, *connect.Request[distribution.AttachSubscriptionRequest]) (*connect.Response[distribution.AttachSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.AttachSubscription is not implemented"))
}

func (UnimplementedDeliveryHandler) DetachSubscription(context.Context, *connect.Request[distribution.DetachSubscriptionRequest]) (*connect.Response[distribution.DetachSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.DetachSubscription is not implemented"))
}

func (UnimplementedDeliveryHandler) RewindSubscription(context.Context, *connect.Request[distribution.RewindSubscriptionRequest]) (*connect.Response[distribution.RewindSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.RewindSubscription is not implemented"))
}

func (UnimplementedDeliveryHandler) GetCatchupStatus(context.Context, *connect.Request[distribution.GetCatchupStatusRequest]) (*connect.Response[distribution.GetCatchupStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.GetCatchupStatus is not implemented"))
}

func (UnimplementedDeliveryHandler) ResumeDestination(context.Context, *connect.Request[distribution.ResumeDestinationRequest]) (*connect.Response[distribution.ResumeDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.ResumeDestination is not implemented"))
}

func (UnimplementedDeliveryHandler) SuspendSubscriptions(context.Context, *connect.Request[distribution.SuspendSubscriptionsRequest]) (*connect.Response[distribution.SuspendSubscriptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.SuspendSubscriptions is not implemented"))
}

func (UnimplementedDeliveryHandler) ResumeSubscriptions(context.Context, *connect.Request[distribution.ResumeSubscriptionsRequest]) (*connect.Response[distribution.ResumeSubscriptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.ResumeSubscriptions is not implemented"))
}

func (UnimplementedDeliveryHandler) SkipDeliveryMatcher(context.Context, *connect.Request[distribution.SkipDeliveryMatcherRequest]) (*connect.Response[distribution.SkipDeliveryMatcherResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.SkipDeliveryMatcher is not implemented"))
}

func (UnimplementedDeliveryHandler) RotateDeliveryKeys(context.Context, *connect.Request[distribution.RotateDeliveryKeysRequest]) (*connect.Response[distribution.RotateDeliveryKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.RotateDeliveryKeys is not implemented"))
}

func (UnimplementedDeliveryHandler) ListDeliveryOperations(context.Context, *connect.Request[distribution.ListDeliveryOperationsRequest]) (*connect.Response[distribution.ListDeliveryOperationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Delivery.ListDeliveryOperations is not implemented"))
}
