// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: distribution/subscriptions.proto

package distributionconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	distribution "github.com/ttab/elephant-public-api/distribution"
	http "net/http"
)

// NewSubscriptionsServiceHandler builds an HTTP handler for the elephant.distribution.Subscriptions
// service from an implementation of the plain distribution.Subscriptions interface, and returns the
// path to mount it on together with the handler, just like NewSubscriptionsHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewSubscriptionsServiceHandler(svc distribution.Subscriptions, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewSubscriptionsHandler(&subscriptionsServiceHandler{svc: svc}, opts...)
}

// subscriptionsServiceHandler implements SubscriptionsHandler on top of a
// distribution.Subscriptions.
type subscriptionsServiceHandler struct {
	svc distribution.Subscriptions
}

func (h *subscriptionsServiceHandler) CreateSubscription(ctx context.Context, req *connect.Request[distribution.CreateSubscriptionRequest]) (*connect.Response[distribution.CreateSubscriptionResponse], error) {
	res, err := h.svc.CreateSubscription(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) UpdateSubscription(ctx context.Context, req *connect.Request[distribution.UpdateSubscriptionRequest]) (*connect.Response[distribution.UpdateSubscriptionResponse], error) {
	res, err := h.svc.UpdateSubscription(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) DeleteSubscription(ctx context.Context, req *connect.Request[distribution.DeleteSubscriptionRequest]) (*connect.Response[distribution.DeleteSubscriptionResponse], error) {
	res, err := h.svc.DeleteSubscription(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) GetSubscription(ctx context.Context, req *connect.Request[distribution.GetSubscriptionRequest]) (*connect.Response[distribution.GetSubscriptionResponse], error) {
	res, err := h.svc.GetSubscription(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) ListSubscriptions(ctx context.Context, req *connect.Request[distribution.ListSubscriptionsRequest]) (*connect.Response[distribution.ListSubscriptionsResponse], error) {
	res, err := h.svc.ListSubscriptions(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) GetDeliveryFields(ctx context.Context, req *connect.Request[distribution.GetDeliveryFieldsRequest]) (*connect.Response[distribution.GetDeliveryFieldsResponse], error) {
	res, err := h.svc.GetDeliveryFields(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) TouchSubscription(ctx context.Context, req *connect.Request[distribution.TouchSubscriptionRequest]) (*connect.Response[distribution.TouchSubscriptionResponse], error) {
	res, err := h.svc.TouchSubscription(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) PollMatches(ctx context.Context, req *connect.Request[distribution.PollMatchesRequest]) (*connect.Response[distribution.PollMatchesResponse], error) {
	res, err := h.svc.PollMatches(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) CalibrateVectorClause(ctx context.Context, req *connect.Request[distribution.CalibrateVectorClauseRequest]) (*connect.Response[distribution.CalibrateVectorClauseResponse], error) {
	res, err := h.svc.CalibrateVectorClause(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *subscriptionsServiceHandler) PreviewSubscription(ctx context.Context, req *connect.Request[distribution.PreviewSubscriptionRequest]) (*connect.Response[distribution.PreviewSubscriptionResponse], error) {
	res, err := h.svc.PreviewSubscription(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewSubscriptionsServiceClient constructs a client for the elephant.distribution.Subscriptions
// service that implements the plain distribution.Subscriptions interface, so that it is a drop-in
// for the Twirp clients. The options are the ones NewSubscriptionsClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewSubscriptionsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) distribution.Subscriptions {
	return &subscriptionsServiceClient{
		client: NewSubscriptionsClient(httpClient, baseURL, opts...),
	}
}

// subscriptionsServiceClient implements distribution.Subscriptions on top of a SubscriptionsClient.
type subscriptionsServiceClient struct {
	client SubscriptionsClient
}

func (c *subscriptionsServiceClient) CreateSubscription(ctx context.Context, req *distribution.CreateSubscriptionRequest) (*distribution.CreateSubscriptionResponse, error) {
	res, err := c.client.CreateSubscription(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) UpdateSubscription(ctx context.Context, req *distribution.UpdateSubscriptionRequest) (*distribution.UpdateSubscriptionResponse, error) {
	res, err := c.client.UpdateSubscription(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) DeleteSubscription(ctx context.Context, req *distribution.DeleteSubscriptionRequest) (*distribution.DeleteSubscriptionResponse, error) {
	res, err := c.client.DeleteSubscription(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) GetSubscription(ctx context.Context, req *distribution.GetSubscriptionRequest) (*distribution.GetSubscriptionResponse, error) {
	res, err := c.client.GetSubscription(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) ListSubscriptions(ctx context.Context, req *distribution.ListSubscriptionsRequest) (*distribution.ListSubscriptionsResponse, error) {
	res, err := c.client.ListSubscriptions(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) GetDeliveryFields(ctx context.Context, req *distribution.GetDeliveryFieldsRequest) (*distribution.GetDeliveryFieldsResponse, error) {
	res, err := c.client.GetDeliveryFields(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) TouchSubscription(ctx context.Context, req *distribution.TouchSubscriptionRequest) (*distribution.TouchSubscriptionResponse, error) {
	res, err := c.client.TouchSubscription(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) PollMatches(ctx context.Context, req *distribution.PollMatchesRequest) (*distribution.PollMatchesResponse, error) {
	res, err := c.client.PollMatches(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) CalibrateVectorClause(ctx context.Context, req *distribution.CalibrateVectorClauseRequest) (*distribution.CalibrateVectorClauseResponse, error) {
	res, err := c.client.CalibrateVectorClause(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *subscriptionsServiceClient) PreviewSubscription(ctx context.Context, req *distribution.PreviewSubscriptionRequest) (*distribution.PreviewSubscriptionResponse, error) {
	res, err := c.client.PreviewSubscription(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
