// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: distribution/subscriptions.proto

package distributionconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	distribution "github.com/ttab/elephant-public-api/distribution"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SubscriptionsName is the fully-qualified name of the Subscriptions service.
	SubscriptionsName = "elephant.distribution.Subscriptions"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SubscriptionsCreateSubscriptionProcedure is the fully-qualified name of the Subscriptions's
	// CreateSubscription RPC.
	SubscriptionsCreateSubscriptionProcedure = "/elephant.distribution.Subscriptions/CreateSubscription"
	// SubscriptionsUpdateSubscriptionProcedure is the fully-qualified name of the Subscriptions's
	// UpdateSubscription RPC.
	SubscriptionsUpdateSubscriptionProcedure = "/elephant.distribution.Subscriptions/UpdateSubscription"
	// SubscriptionsDeleteSubscriptionProcedure is the fully-qualified name of the Subscriptions's
	// DeleteSubscription RPC.
	SubscriptionsDeleteSubscriptionProcedure = "/elephant.distribution.Subscriptions/DeleteSubscription"
	// SubscriptionsGetSubscriptionProcedure is the fully-qualified name of the Subscriptions's
	// GetSubscription RPC.
	SubscriptionsGetSubscriptionProcedure = "/elephant.distribution.Subscriptions/GetSubscription"
	// SubscriptionsListSubscriptionsProcedure is the fully-qualified name of the Subscriptions's
	// ListSubscriptions RPC.
	SubscriptionsListSubscriptionsProcedure = "/elephant.distribution.Subscriptions/ListSubscriptions"
	// SubscriptionsGetDeliveryFieldsProcedure is the fully-qualified name of the Subscriptions's
	// GetDeliveryFields RPC.
	SubscriptionsGetDeliveryFieldsProcedure = "/elephant.distribution.Subscriptions/GetDeliveryFields"
	// SubscriptionsTouchSubscriptionProcedure is the fully-qualified name of the Subscriptions's
	// TouchSubscription RPC.
	SubscriptionsTouchSubscriptionProcedure = "/elephant.distribution.Subscriptions/TouchSubscription"
	// SubscriptionsPollMatchesProcedure is the fully-qualified name of the Subscriptions's PollMatches
	// RPC.
	SubscriptionsPollMatchesProcedure = "/elephant.distribution.Subscriptions/PollMatches"
	// SubscriptionsCalibrateVectorClauseProcedure is the fully-qualified name of the Subscriptions's
	// CalibrateVectorClause RPC.
	SubscriptionsCalibrateVectorClauseProcedure = "/elephant.distribution.Subscriptions/CalibrateVectorClause"
	// SubscriptionsPreviewSubscriptionProcedure is the fully-qualified name of the Subscriptions's
	// PreviewSubscription RPC.
	SubscriptionsPreviewSubscriptionProcedure = "/elephant.distribution.Subscriptions/PreviewSubscription"
)

// SubscriptionsClient is a client for the elephant.distribution.Subscriptions service.
type SubscriptionsClient interface {
	// CreateSubscription registers a new subscription and returns it as
	// stored, with the ownership and expiry the server assigned to it.
	// Matching starts at the next indexed document; documents that were
	// indexed before the call are never matched, use PreviewSubscription to
	// see what the subscription would have caught.
	CreateSubscription(context.Context, *connect.Request[distribution.CreateSubscriptionRequest]) (*connect.Response[distribution.CreateSubscriptionResponse], error)
	// UpdateSubscription replaces the definition of a subscription. The
	// spec is written whole: fields left out of it are cleared, not kept.
	// Vector clause members are re-embedded and the query part is
	// re-translated, so an update takes effect for documents indexed after
	// it returns. Counts as a touch.
	UpdateSubscription(context.Context, *connect.Request[distribution.UpdateSubscriptionRequest]) (*connect.Response[distribution.UpdateSubscriptionResponse], error)
	// DeleteSubscription removes a subscription and its match log. Deleting
	// is permanent and distinct from a subscription expiring: polling a
	// deleted subscription is a not-found, polling an expired one is a
	// failed precondition.
	DeleteSubscription(context.Context, *connect.Request[distribution.DeleteSubscriptionRequest]) (*connect.Response[distribution.DeleteSubscriptionResponse], error)
	// GetSubscription returns a subscription as stored. Counts as a touch.
	GetSubscription(context.Context, *connect.Request[distribution.GetSubscriptionRequest]) (*connect.Response[distribution.GetSubscriptionResponse], error)
	// ListSubscriptions lists the subscriptions the caller can see: the
	// ones owned by the organisation of the caller, and the ones owned by
	// the calling subject. Listing does not count as a touch, so it is safe
	// to poll for housekeeping without keeping abandoned subscriptions
	// alive.
	ListSubscriptions(context.Context, *connect.Request[distribution.ListSubscriptionsRequest]) (*connect.Response[distribution.ListSubscriptionsResponse], error)
	// GetDeliveryFields returns the delivery-field vocabulary of the active
	// configuration generation: the names a rule may reference, what kind
	// of condition each admits, and which document types declare it.
	//
	// The last of those is what an editor needs to warn with. A condition
	// on a field only some of a subscription's document types declare is a
	// no-match on the rest, silently, because an absent key is a no-match
	// by definition - so a rule over {article, planning-item} naming a
	// field only articles declare delivers half of what it looks like it
	// delivers.
	//
	// The registry is read from Postgres and needs no index. Listing does
	// not count as a touch on anything.
	GetDeliveryFields(context.Context, *connect.Request[distribution.GetDeliveryFieldsRequest]) (*connect.Response[distribution.GetDeliveryFieldsResponse], error)
	// TouchSubscription resets the keep-alive clock of a subscription
	// without reading anything else. Ordinary use does not need it -
	// PollMatches, GetSubscription and UpdateSubscription all count as
	// touches - it is for clients that hold a subscription open while they
	// are not polling. Touching a durable subscription is a no-op, it has
	// no clock to reset.
	TouchSubscription(context.Context, *connect.Request[distribution.TouchSubscriptionRequest]) (*connect.Response[distribution.TouchSubscriptionResponse], error)
	// PollMatches reads the match log of a subscription, long-polling for
	// new matches. Delivery is at-least-once and ordered by event ID, which
	// doubles as the cursor: pass the highest event ID you have processed
	// as after_event_id on the next call.
	//
	// Polling a subscription that has expired is a failed precondition,
	// not a not-found: the subscription was abandoned rather
	// than deleted, and the client can tell the two apart and re-create if
	// it wants to. Counts as a touch, so a client that keeps polling never
	// expires.
	PollMatches(context.Context, *connect.Request[distribution.PollMatchesRequest]) (*connect.Response[distribution.PollMatchesResponse], error)
	// CalibrateVectorClause is how a min_similarity gets chosen. It scores
	// the given clause members against the documents of a recent window and
	// returns the similarity distribution, the top hits to eyeball, and -
	// the number the decision is actually made on - the estimated matches
	// per day at a ladder of candidate thresholds. "At 0.62 this clause
	// alone would have matched about 14 documents a day last week" is what
	// a threshold means in practice; a suggested threshold is a volume
	// target, never a claim about relevance.
	CalibrateVectorClause(context.Context, *connect.Request[distribution.CalibrateVectorClauseRequest]) (*connect.Response[distribution.CalibrateVectorClauseResponse], error)
	// PreviewSubscription is the dry run of a complete subscription
	// definition against a recent window: what would have matched, with the
	// same provenance the match log carries. It is the acceptance test for
	// a new subscription, and the only practical way to reason about a
	// negated clause, which is invisible in the results it does not
	// exclude.
	PreviewSubscription(context.Context, *connect.Request[distribution.PreviewSubscriptionRequest]) (*connect.Response[distribution.PreviewSubscriptionResponse], error)
}

// NewSubscriptionsClient constructs a client for the elephant.distribution.Subscriptions service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSubscriptionsClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SubscriptionsClient {
	baseURL = strings.TrimRight(baseURL, "/")
	subscriptionsMethods := distribution.File_distribution_subscriptions_proto.Services().ByName("Subscriptions").Methods()
	return &subscriptionsClient{
		createSubscription: connect.NewClient[distribution.CreateSubscriptionRequest, distribution.CreateSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionsCreateSubscriptionProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("CreateSubscription")),
			connect.WithClientOptions(opts...),
		),
		updateSubscription: connect.NewClient[distribution.UpdateSubscriptionRequest, distribution.UpdateSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionsUpdateSubscriptionProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("UpdateSubscription")),
			connect.WithClientOptions(opts...),
		),
		deleteSubscription: connect.NewClient[distribution.DeleteSubscriptionRequest, distribution.DeleteSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionsDeleteSubscriptionProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("DeleteSubscription")),
			connect.WithClientOptions(opts...),
		),
		getSubscription: connect.NewClient[distribution.GetSubscriptionRequest, distribution.GetSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionsGetSubscriptionProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("GetSubscription")),
			connect.WithClientOptions(opts...),
		),
		listSubscriptions: connect.NewClient[distribution.ListSubscriptionsRequest, distribution.ListSubscriptionsResponse](
			httpClient,
			baseURL+SubscriptionsListSubscriptionsProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("ListSubscriptions")),
			connect.WithClientOptions(opts...),
		),
		getDeliveryFields: connect.NewClient[distribution.GetDeliveryFieldsRequest, distribution.GetDeliveryFieldsResponse](
			httpClient,
			baseURL+SubscriptionsGetDeliveryFieldsProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("GetDeliveryFields")),
			connect.WithClientOptions(opts...),
		),
		touchSubscription: connect.NewClient[distribution.TouchSubscriptionRequest, distribution.TouchSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionsTouchSubscriptionProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("TouchSubscription")),
			connect.WithClientOptions(opts...),
		),
		pollMatches: connect.NewClient[distribution.PollMatchesRequest, distribution.PollMatchesResponse](
			httpClient,
			baseURL+SubscriptionsPollMatchesProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("PollMatches")),
			connect.WithClientOptions(opts...),
		),
		calibrateVectorClause: connect.NewClient[distribution.CalibrateVectorClauseRequest, distribution.CalibrateVectorClauseResponse](
			httpClient,
			baseURL+SubscriptionsCalibrateVectorClauseProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("CalibrateVectorClause")),
			connect.WithClientOptions(opts...),
		),
		previewSubscription: connect.NewClient[distribution.PreviewSubscriptionRequest, distribution.PreviewSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionsPreviewSubscriptionProcedure,
			connect.WithSchema(subscriptionsMethods.ByName("PreviewSubscription")),
			connect.WithClientOptions(opts...),
		),
	}
}

// subscriptionsClient implements SubscriptionsClient.
type subscriptionsClient struct {
	createSubscription    *connect.Client[distribution.CreateSubscriptionRequest, distribution.CreateSubscriptionResponse]
	updateSubscription    *connect.Client[distribution.UpdateSubscriptionRequest, distribution.UpdateSubscriptionResponse]
	deleteSubscription    *connect.Client[distribution.DeleteSubscriptionRequest, distribution.DeleteSubscriptionResponse]
	getSubscription       *connect.Client[distribution.GetSubscriptionRequest, distribution.GetSubscriptionResponse]
	listSubscriptions     *connect.Client[distribution.ListSubscriptionsRequest, distribution.ListSubscriptionsResponse]
	getDeliveryFields     *connect.Client[distribution.GetDeliveryFieldsRequest, distribution.GetDeliveryFieldsResponse]
	touchSubscription     *connect.Client[distribution.TouchSubscriptionRequest, distribution.TouchSubscriptionResponse]
	pollMatches           *connect.Client[distribution.PollMatchesRequest, distribution.PollMatchesResponse]
	calibrateVectorClause *connect.Client[distribution.CalibrateVectorClauseRequest, distribution.CalibrateVectorClauseResponse]
	previewSubscription   *connect.Client[distribution.PreviewSubscriptionRequest, distribution.PreviewSubscriptionResponse]
}

// CreateSubscription calls elephant.distribution.Subscriptions.CreateSubscription.
func (c *subscriptionsClient) CreateSubscription(ctx context.Context, req *connect.Request[distribution.CreateSubscriptionRequest]) (*connect.Response[distribution.CreateSubscriptionResponse], error) {
	return c.createSubscription.CallUnary(ctx, req)
}

// UpdateSubscription calls elephant.distribution.Subscriptions.UpdateSubscription.
func (c *subscriptionsClient) UpdateSubscription(ctx context.Context, req *connect.Request[distribution.UpdateSubscriptionRequest]) (*connect.Response[distribution.UpdateSubscriptionResponse], error) {
	return c.updateSubscription.CallUnary(ctx, req)
}

// DeleteSubscription calls elephant.distribution.Subscriptions.DeleteSubscription.
func (c *subscriptionsClient) DeleteSubscription(ctx context.Context, req *connect.Request[distribution.DeleteSubscriptionRequest]) (*connect.Response[distribution.DeleteSubscriptionResponse], error) {
	return c.deleteSubscription.CallUnary(ctx, req)
}

// GetSubscription calls elephant.distribution.Subscriptions.GetSubscription.
func (c *subscriptionsClient) GetSubscription(ctx context.Context, req *connect.Request[distribution.GetSubscriptionRequest]) (*connect.Response[distribution.GetSubscriptionResponse], error) {
	return c.getSubscription.CallUnary(ctx, req)
}

// ListSubscriptions calls elephant.distribution.Subscriptions.ListSubscriptions.
func (c *subscriptionsClient) ListSubscriptions(ctx context.Context, req *connect.Request[distribution.ListSubscriptionsRequest]) (*connect.Response[distribution.ListSubscriptionsResponse], error) {
	return c.listSubscriptions.CallUnary(ctx, req)
}

// GetDeliveryFields calls elephant.distribution.Subscriptions.GetDeliveryFields.
func (c *subscriptionsClient) GetDeliveryFields(ctx context.Context, req *connect.Request[distribution.GetDeliveryFieldsRequest]) (*connect.Response[distribution.GetDeliveryFieldsResponse], error) {
	return c.getDeliveryFields.CallUnary(ctx, req)
}

// TouchSubscription calls elephant.distribution.Subscriptions.TouchSubscription.
func (c *subscriptionsClient) TouchSubscription(ctx context.Context, req *connect.Request[distribution.TouchSubscriptionRequest]) (*connect.Response[distribution.TouchSubscriptionResponse], error) {
	return c.touchSubscription.CallUnary(ctx, req)
}

// PollMatches calls elephant.distribution.Subscriptions.PollMatches.
func (c *subscriptionsClient) PollMatches(ctx context.Context, req *connect.Request[distribution.PollMatchesRequest]) (*connect.Response[distribution.PollMatchesResponse], error) {
	return c.pollMatches.CallUnary(ctx, req)
}

// CalibrateVectorClause calls elephant.distribution.Subscriptions.CalibrateVectorClause.
func (c *subscriptionsClient) CalibrateVectorClause(ctx context.Context, req *connect.Request[distribution.CalibrateVectorClauseRequest]) (*connect.Response[distribution.CalibrateVectorClauseResponse], error) {
	return c.calibrateVectorClause.CallUnary(ctx, req)
}

// PreviewSubscription calls elephant.distribution.Subscriptions.PreviewSubscription.
func (c *subscriptionsClient) PreviewSubscription(ctx context.Context, req *connect.Request[distribution.PreviewSubscriptionRequest]) (*connect.Response[distribution.PreviewSubscriptionResponse], error) {
	return c.previewSubscription.CallUnary(ctx, req)
}

// SubscriptionsHandler is an implementation of the elephant.distribution.Subscriptions service.
type SubscriptionsHandler interface {
	// CreateSubscription registers a new subscription and returns it as
	// stored, with the ownership and expiry the server assigned to it.
	// Matching starts at the next indexed document; documents that were
	// indexed before the call are never matched, use PreviewSubscription to
	// see what the subscription would have caught.
	CreateSubscription(context.Context, *connect.Request[distribution.CreateSubscriptionRequest]) (*connect.Response[distribution.CreateSubscriptionResponse], error)
	// UpdateSubscription replaces the definition of a subscription. The
	// spec is written whole: fields left out of it are cleared, not kept.
	// Vector clause members are re-embedded and the query part is
	// re-translated, so an update takes effect for documents indexed after
	// it returns. Counts as a touch.
	UpdateSubscription(context.Context, *connect.Request[distribution.UpdateSubscriptionRequest]) (*connect.Response[distribution.UpdateSubscriptionResponse], error)
	// DeleteSubscription removes a subscription and its match log. Deleting
	// is permanent and distinct from a subscription expiring: polling a
	// deleted subscription is a not-found, polling an expired one is a
	// failed precondition.
	DeleteSubscription(context.Context, *connect.Request[distribution.DeleteSubscriptionRequest]) (*connect.Response[distribution.DeleteSubscriptionResponse], error)
	// GetSubscription returns a subscription as stored. Counts as a touch.
	GetSubscription(context.Context, *connect.Request[distribution.GetSubscriptionRequest]) (*connect.Response[distribution.GetSubscriptionResponse], error)
	// ListSubscriptions lists the subscriptions the caller can see: the
	// ones owned by the organisation of the caller, and the ones owned by
	// the calling subject. Listing does not count as a touch, so it is safe
	// to poll for housekeeping without keeping abandoned subscriptions
	// alive.
	ListSubscriptions(context.Context, *connect.Request[distribution.ListSubscriptionsRequest]) (*connect.Response[distribution.ListSubscriptionsResponse], error)
	// GetDeliveryFields returns the delivery-field vocabulary of the active
	// configuration generation: the names a rule may reference, what kind
	// of condition each admits, and which document types declare it.
	//
	// The last of those is what an editor needs to warn with. A condition
	// on a field only some of a subscription's document types declare is a
	// no-match on the rest, silently, because an absent key is a no-match
	// by definition - so a rule over {article, planning-item} naming a
	// field only articles declare delivers half of what it looks like it
	// delivers.
	//
	// The registry is read from Postgres and needs no index. Listing does
	// not count as a touch on anything.
	GetDeliveryFields(context.Context, *connect.Request[distribution.GetDeliveryFieldsRequest]) (*connect.Response[distribution.GetDeliveryFieldsResponse], error)
	// TouchSubscription resets the keep-alive clock of a subscription
	// without reading anything else. Ordinary use does not need it -
	// PollMatches, GetSubscription and UpdateSubscription all count as
	// touches - it is for clients that hold a subscription open while they
	// are not polling. Touching a durable subscription is a no-op, it has
	// no clock to reset.
	TouchSubscription(context.Context, *connect.Request[distribution.TouchSubscriptionRequest]) (*connect.Response[distribution.TouchSubscriptionResponse], error)
	// PollMatches reads the match log of a subscription, long-polling for
	// new matches. Delivery is at-least-once and ordered by event ID, which
	// doubles as the cursor: pass the highest event ID you have processed
	// as after_event_id on the next call.
	//
	// Polling a subscription that has expired is a failed precondition,
	// not a not-found: the subscription was abandoned rather
	// than deleted, and the client can tell the two apart and re-create if
	// it wants to. Counts as a touch, so a client that keeps polling never
	// expires.
	PollMatches(context.Context, *connect.Request[distribution.PollMatchesRequest]) (*connect.Response[distribution.PollMatchesResponse], error)
	// CalibrateVectorClause is how a min_similarity gets chosen. It scores
	// the given clause members against the documents of a recent window and
	// returns the similarity distribution, the top hits to eyeball, and -
	// the number the decision is actually made on - the estimated matches
	// per day at a ladder of candidate thresholds. "At 0.62 this clause
	// alone would have matched about 14 documents a day last week" is what
	// a threshold means in practice; a suggested threshold is a volume
	// target, never a claim about relevance.
	CalibrateVectorClause(context.Context, *connect.Request[distribution.CalibrateVectorClauseRequest]) (*connect.Response[distribution.CalibrateVectorClauseResponse], error)
	// PreviewSubscription is the dry run of a complete subscription
	// definition against a recent window: what would have matched, with the
	// same provenance the match log carries. It is the acceptance test for
	// a new subscription, and the only practical way to reason about a
	// negated clause, which is invisible in the results it does not
	// exclude.
	PreviewSubscription(context.Context, *connect.Request[distribution.PreviewSubscriptionRequest]) (*connect.Response[distribution.PreviewSubscriptionResponse], error)
}

// NewSubscriptionsHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSubscriptionsHandler(svc SubscriptionsHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	subscriptionsMethods := distribution.File_distribution_subscriptions_proto.Services().ByName("Subscriptions").Methods()
	subscriptionsCreateSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionsCreateSubscriptionProcedure,
		svc.CreateSubscription,
		connect.WithSchema(subscriptionsMethods.ByName("CreateSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsUpdateSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionsUpdateSubscriptionProcedure,
		svc.UpdateSubscription,
		connect.WithSchema(subscriptionsMethods.ByName("UpdateSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsDeleteSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionsDeleteSubscriptionProcedure,
		svc.DeleteSubscription,
		connect.WithSchema(subscriptionsMethods.ByName("DeleteSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsGetSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionsGetSubscriptionProcedure,
		svc.GetSubscription,
		connect.WithSchema(subscriptionsMethods.ByName("GetSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsListSubscriptionsHandler := connect.NewUnaryHandler(
		SubscriptionsListSubscriptionsProcedure,
		svc.ListSubscriptions,
		connect.WithSchema(subscriptionsMethods.ByName("ListSubscriptions")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsGetDeliveryFieldsHandler := connect.NewUnaryHandler(
		SubscriptionsGetDeliveryFieldsProcedure,
		svc.GetDeliveryFields,
		connect.WithSchema(subscriptionsMethods.ByName("GetDeliveryFields")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsTouchSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionsTouchSubscriptionProcedure,
		svc.TouchSubscription,
		connect.WithSchema(subscriptionsMethods.ByName("TouchSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsPollMatchesHandler := connect.NewUnaryHandler(
		SubscriptionsPollMatchesProcedure,
		svc.PollMatches,
		connect.WithSchema(subscriptionsMethods.ByName("PollMatches")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsCalibrateVectorClauseHandler := connect.NewUnaryHandler(
		SubscriptionsCalibrateVectorClauseProcedure,
		svc.CalibrateVectorClause,
		connect.WithSchema(subscriptionsMethods.ByName("CalibrateVectorClause")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionsPreviewSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionsPreviewSubscriptionProcedure,
		svc.PreviewSubscription,
		connect.WithSchema(subscriptionsMethods.ByName("PreviewSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephant.distribution.Subscriptions/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SubscriptionsCreateSubscriptionProcedure:
			subscriptionsCreateSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionsUpdateSubscriptionProcedure:
			subscriptionsUpdateSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionsDeleteSubscriptionProcedure:
			subscriptionsDeleteSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionsGetSubscriptionProcedure:
			subscriptionsGetSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionsListSubscriptionsProcedure:
			subscriptionsListSubscriptionsHandler.ServeHTTP(w, r)
		case SubscriptionsGetDeliveryFieldsProcedure:
			subscriptionsGetDeliveryFieldsHandler.ServeHTTP(w, r)
		case SubscriptionsTouchSubscriptionProcedure:
			subscriptionsTouchSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionsPollMatchesProcedure:
			subscriptionsPollMatchesHandler.ServeHTTP(w, r)
		case SubscriptionsCalibrateVectorClauseProcedure:
			subscriptionsCalibrateVectorClauseHandler.ServeHTTP(w, r)
		case SubscriptionsPreviewSubscriptionProcedure:
			subscriptionsPreviewSubscriptionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSubscriptionsHandler returns CodeUnimplemented from all methods.
type UnimplementedSubscriptionsHandler struct{}

func (UnimplementedSubscriptionsHandler) CreateSubscription(context.Context, *connect.Request[distribution.CreateSubscriptionRequest]) (*connect.Response[distribution.CreateSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.CreateSubscription is not implemented"))
}

func (UnimplementedSubscriptionsHandler) UpdateSubscription(context.Context, *connect.Request[distribution.UpdateSubscriptionRequest]) (*connect.Response[distribution.UpdateSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.UpdateSubscription is not implemented"))
}

func (UnimplementedSubscriptionsHandler) DeleteSubscription(context.Context, *connect.Request[distribution.DeleteSubscriptionRequest]) (*connect.Response[distribution.DeleteSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.DeleteSubscription is not implemented"))
}

func (UnimplementedSubscriptionsHandler) GetSubscription(context.Context, *connect.Request[distribution.GetSubscriptionRequest]) (*connect.Response[distribution.GetSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.GetSubscription is not implemented"))
}

func (UnimplementedSubscriptionsHandler) ListSubscriptions(context.Context, *connect.Request[distribution.ListSubscriptionsRequest]) (*connect.Response[distribution.ListSubscriptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.ListSubscriptions is not implemented"))
}

func (UnimplementedSubscriptionsHandler) GetDeliveryFields(context.Context, *connect.Request[distribution.GetDeliveryFieldsRequest]) (*connect.Response[distribution.GetDeliveryFieldsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.GetDeliveryFields is not implemented"))
}

func (UnimplementedSubscriptionsHandler) TouchSubscription(context.Context, *connect.Request[distribution.TouchSubscriptionRequest]) (*connect.Response[distribution.TouchSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.TouchSubscription is not implemented"))
}

func (UnimplementedSubscriptionsHandler) PollMatches(context.Context, *connect.Request[distribution.PollMatchesRequest]) (*connect.Response[distribution.PollMatchesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.PollMatches is not implemented"))
}

func (UnimplementedSubscriptionsHandler) CalibrateVectorClause(context.Context, *connect.Request[distribution.CalibrateVectorClauseRequest]) (*connect.Response[distribution.CalibrateVectorClauseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.CalibrateVectorClause is not implemented"))
}

func (UnimplementedSubscriptionsHandler) PreviewSubscription(context.Context, *connect.Request[distribution.PreviewSubscriptionRequest]) (*connect.Response[distribution.PreviewSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.distribution.Subscriptions.PreviewSubscription is not implemented"))
}
