// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v4.24.4
// source: assets/service.proto

package assets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSigningKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningKeysRequest) Reset() {
	*x = GetSigningKeysRequest{}
	mi := &file_assets_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningKeysRequest) ProtoMessage() {}

func (x *GetSigningKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningKeysRequest.ProtoReflect.Descriptor instead.
func (*GetSigningKeysRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{0}
}

type GetSigningKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*SigningKey          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningKeysResponse) Reset() {
	*x = GetSigningKeysResponse{}
	mi := &file_assets_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningKeysResponse) ProtoMessage() {}

func (x *GetSigningKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningKeysResponse.ProtoReflect.Descriptor instead.
func (*GetSigningKeysResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSigningKeysResponse) GetKeys() []*SigningKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SigningKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kid is the key identifier carried in minted tokens.
	Kid string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// Secret is the hex-encoded HMAC key material.
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// NotBefore is the start of the validity window, unix seconds.
	NotBefore int64 `protobuf:"varint,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	// NotAfter is the end of the validity window, unix seconds.
	NotAfter int64 `protobuf:"varint,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// Use is "delivery" for routinely rotated delivery keys or "public"
	// for the long-lived key that signs permanent public URLs.
	Use           string `protobuf:"bytes,5,opt,name=use,proto3" json:"use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningKey) Reset() {
	*x = SigningKey{}
	mi := &file_assets_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKey) ProtoMessage() {}

func (x *SigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKey.ProtoReflect.Descriptor instead.
func (*SigningKey) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{2}
}

func (x *SigningKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *SigningKey) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SigningKey) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *SigningKey) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *SigningKey) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

var File_assets_service_proto protoreflect.FileDescriptor

var file_assets_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6e, 0x6f, 0x74, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x6f, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x6e, 0x6f, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x73, 0x65, 0x32, 0x61, 0x0a, 0x04, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67,
	0x4b, 0x65, 0x79, 0x73, 0x12, 0x22, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x74, 0x61, 0x62,
	0x2f, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_assets_service_proto_rawDescOnce sync.Once
	file_assets_service_proto_rawDescData = file_assets_service_proto_rawDesc
)

func file_assets_service_proto_rawDescGZIP() []byte {
	file_assets_service_proto_rawDescOnce.Do(func() {
		file_assets_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_assets_service_proto_rawDescData)
	})
	return file_assets_service_proto_rawDescData
}

var file_assets_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_assets_service_proto_goTypes = []any{
	(*GetSigningKeysRequest)(nil),  // 0: ttab.assets.GetSigningKeysRequest
	(*GetSigningKeysResponse)(nil), // 1: ttab.assets.GetSigningKeysResponse
	(*SigningKey)(nil),             // 2: ttab.assets.SigningKey
}
var file_assets_service_proto_depIdxs = []int32{
	2, // 0: ttab.assets.GetSigningKeysResponse.keys:type_name -> ttab.assets.SigningKey
	0, // 1: ttab.assets.Keys.GetSigningKeys:input_type -> ttab.assets.GetSigningKeysRequest
	1, // 2: ttab.assets.Keys.GetSigningKeys:output_type -> ttab.assets.GetSigningKeysResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_assets_service_proto_init() }
func file_assets_service_proto_init() {
	if File_assets_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_assets_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assets_service_proto_goTypes,
		DependencyIndexes: file_assets_service_proto_depIdxs,
		MessageInfos:      file_assets_service_proto_msgTypes,
	}.Build()
	File_assets_service_proto = out.File
	file_assets_service_proto_rawDesc = nil
	file_assets_service_proto_goTypes = nil
	file_assets_service_proto_depIdxs = nil
}
