// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v4.24.4
// source: assets/service.proto

package assets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSigningKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningKeysRequest) Reset() {
	*x = GetSigningKeysRequest{}
	mi := &file_assets_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningKeysRequest) ProtoMessage() {}

func (x *GetSigningKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningKeysRequest.ProtoReflect.Descriptor instead.
func (*GetSigningKeysRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{0}
}

type GetSigningKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*SigningKey          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningKeysResponse) Reset() {
	*x = GetSigningKeysResponse{}
	mi := &file_assets_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningKeysResponse) ProtoMessage() {}

func (x *GetSigningKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningKeysResponse.ProtoReflect.Descriptor instead.
func (*GetSigningKeysResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSigningKeysResponse) GetKeys() []*SigningKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetVariantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariantsRequest) Reset() {
	*x = GetVariantsRequest{}
	mi := &file_assets_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariantsRequest) ProtoMessage() {}

func (x *GetVariantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariantsRequest.ProtoReflect.Descriptor instead.
func (*GetVariantsRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{2}
}

type GetVariantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variants      []*Variant             `protobuf:"bytes,1,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariantsResponse) Reset() {
	*x = GetVariantsResponse{}
	mi := &file_assets_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariantsResponse) ProtoMessage() {}

func (x *GetVariantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariantsResponse.ProtoReflect.Descriptor instead.
func (*GetVariantsResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetVariantsResponse) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type Variant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the variant, used as the variant path segment in asset URLs.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Kind is the asset kind the variant applies to, e.g. "image".
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Max is the bounding box in pixels (longest side) for image variants.
	Max int64 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	// Fit controls how an image is fitted to the bounding box. Only
	// "inside" is defined: scale down to fit, never upscale.
	Fit string `protobuf:"bytes,4,opt,name=fit,proto3" json:"fit,omitempty"`
	// Public marks the variant as a public derivative: reachable by any
	// valid signature and usable with non-expiring (exp=0) tokens.
	Public bool `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	// Scopes are the named access scopes that grant access to the variant
	// (in addition to the reserved _all scope).
	Scopes []string `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Classes are the class names available as a {variant}-{class} suffix,
	// e.g. "wm" makes {variant}-wm a public watermarked rendition.
	Classes       []string `protobuf:"bytes,7,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_assets_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{4}
}

func (x *Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variant) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Variant) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Variant) GetFit() string {
	if x != nil {
		return x.Fit
	}
	return ""
}

func (x *Variant) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Variant) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *Variant) GetClasses() []string {
	if x != nil {
		return x.Classes
	}
	return nil
}

type SigningKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kid is the key identifier carried in minted tokens.
	Kid string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// Secret is the hex-encoded HMAC key material.
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// NotBefore is the start of the validity window, unix seconds.
	NotBefore int64 `protobuf:"varint,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	// NotAfter is the end of the validity window, unix seconds.
	NotAfter int64 `protobuf:"varint,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// Use is "delivery" for routinely rotated delivery keys or "public"
	// for the long-lived key that signs permanent public URLs.
	Use           string `protobuf:"bytes,5,opt,name=use,proto3" json:"use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningKey) Reset() {
	*x = SigningKey{}
	mi := &file_assets_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKey) ProtoMessage() {}

func (x *SigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKey.ProtoReflect.Descriptor instead.
func (*SigningKey) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{5}
}

func (x *SigningKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *SigningKey) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SigningKey) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *SigningKey) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *SigningKey) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

// MetadataField is one recognized field kept on cropped renditions beyond the
// built-in whitelist. Exactly one group of fields applies per kind.
type MetadataField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind is "exif", "iptc", or "xmp".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// ExifIfd selects the EXIF sub-IFD for kind "exif": "ifd0" or "exif".
	ExifIfd string `protobuf:"bytes,2,opt,name=exif_ifd,json=exifIfd,proto3" json:"exif_ifd,omitempty"`
	// Tag is the EXIF tag id for kind "exif" (e.g. 40091). UNDEFINED-typed or
	// oversized values are still dropped by the transform regardless.
	Tag uint32 `protobuf:"varint,3,opt,name=tag,proto3" json:"tag,omitempty"`
	// Dataset is the IPTC-IIM record-2 dataset number for kind "iptc".
	Dataset uint32 `protobuf:"varint,4,opt,name=dataset,proto3" json:"dataset,omitempty"`
	// Namespace is the XMP property namespace URI for kind "xmp".
	Namespace string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Prefix is the preferred XMP serialization prefix for kind "xmp".
	Prefix string `protobuf:"bytes,6,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Local is the XMP property local name for kind "xmp".
	Local string `protobuf:"bytes,7,opt,name=local,proto3" json:"local,omitempty"`
	// Form is the XMP RDF shape for kind "xmp": "simple", "alt", "seq", or
	// "bag".
	Form string `protobuf:"bytes,8,opt,name=form,proto3" json:"form,omitempty"`
	// Alias references a built-in EXIF/IPTC field by name (e.g.
	// "DateTimeOriginal", "By-line"), an alternative to spelling out kind, ifd,
	// tag, or dataset when adding a field. Aliases are defined in code and
	// cannot be created through the API. Ignored for XMP.
	Alias         string `protobuf:"bytes,9,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataField) Reset() {
	*x = MetadataField{}
	mi := &file_assets_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataField) ProtoMessage() {}

func (x *MetadataField) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataField.ProtoReflect.Descriptor instead.
func (*MetadataField) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{6}
}

func (x *MetadataField) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MetadataField) GetExifIfd() string {
	if x != nil {
		return x.ExifIfd
	}
	return ""
}

func (x *MetadataField) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *MetadataField) GetDataset() uint32 {
	if x != nil {
		return x.Dataset
	}
	return 0
}

func (x *MetadataField) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetadataField) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *MetadataField) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *MetadataField) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *MetadataField) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

// DroppedField is one metadata field a crop would drop, as reported by
// InspectCropMetadata.
type DroppedField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field is the concrete descriptor; pass it straight back to
	// AddMetadataField to start preserving it (when addable). Its alias holds
	// the human name for known EXIF/IPTC fields, empty for wholly unknown ones.
	Field *MetadataField `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Id is the raw underlying identifier, always set (e.g. "ifd0/0x9291",
	// "2:0x64", or an XMP "namespace local").
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Value is a readable representation of the field's value, truncated.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Reason is why the field drops ("not in whitelist", "binary value",
	// "embedded thumbnail", ...).
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Addable is true when the field can be preserved by adding it to the
	// whitelist; false for structural drops (thumbnails, binary payloads) that
	// are dropped regardless of configuration.
	Addable       bool `protobuf:"varint,5,opt,name=addable,proto3" json:"addable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroppedField) Reset() {
	*x = DroppedField{}
	mi := &file_assets_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroppedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroppedField) ProtoMessage() {}

func (x *DroppedField) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroppedField.ProtoReflect.Descriptor instead.
func (*DroppedField) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{7}
}

func (x *DroppedField) GetField() *MetadataField {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *DroppedField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DroppedField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DroppedField) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DroppedField) GetAddable() bool {
	if x != nil {
		return x.Addable
	}
	return false
}

type InspectCropMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ns is the source namespace of the asset.
	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	// Id of the asset in the namespace's id scheme.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Version of the asset; defaults to the current version ("0").
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectCropMetadataRequest) Reset() {
	*x = InspectCropMetadataRequest{}
	mi := &file_assets_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectCropMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectCropMetadataRequest) ProtoMessage() {}

func (x *InspectCropMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectCropMetadataRequest.ProtoReflect.Descriptor instead.
func (*InspectCropMetadataRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{8}
}

func (x *InspectCropMetadataRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *InspectCropMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InspectCropMetadataRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InspectCropMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dropped lists the fields a crop would drop, most useful first is not
	// guaranteed — clients should present them grouped by kind.
	Dropped       []*DroppedField `protobuf:"bytes,1,rep,name=dropped,proto3" json:"dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectCropMetadataResponse) Reset() {
	*x = InspectCropMetadataResponse{}
	mi := &file_assets_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectCropMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectCropMetadataResponse) ProtoMessage() {}

func (x *InspectCropMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectCropMetadataResponse.ProtoReflect.Descriptor instead.
func (*InspectCropMetadataResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{9}
}

func (x *InspectCropMetadataResponse) GetDropped() []*DroppedField {
	if x != nil {
		return x.Dropped
	}
	return nil
}

type ListMetadataFieldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetadataFieldsRequest) Reset() {
	*x = ListMetadataFieldsRequest{}
	mi := &file_assets_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetadataFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadataFieldsRequest) ProtoMessage() {}

func (x *ListMetadataFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadataFieldsRequest.ProtoReflect.Descriptor instead.
func (*ListMetadataFieldsRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{10}
}

type ListMetadataFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields are the configured extras (built-in defaults are not listed).
	Fields        []*MetadataField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetadataFieldsResponse) Reset() {
	*x = ListMetadataFieldsResponse{}
	mi := &file_assets_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetadataFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadataFieldsResponse) ProtoMessage() {}

func (x *ListMetadataFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadataFieldsResponse.ProtoReflect.Descriptor instead.
func (*ListMetadataFieldsResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListMetadataFieldsResponse) GetFields() []*MetadataField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type AddMetadataFieldRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to add or update.
	Field         *MetadataField `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetadataFieldRequest) Reset() {
	*x = AddMetadataFieldRequest{}
	mi := &file_assets_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetadataFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetadataFieldRequest) ProtoMessage() {}

func (x *AddMetadataFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetadataFieldRequest.ProtoReflect.Descriptor instead.
func (*AddMetadataFieldRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddMetadataFieldRequest) GetField() *MetadataField {
	if x != nil {
		return x.Field
	}
	return nil
}

type AddMetadataFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetadataFieldResponse) Reset() {
	*x = AddMetadataFieldResponse{}
	mi := &file_assets_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetadataFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetadataFieldResponse) ProtoMessage() {}

func (x *AddMetadataFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetadataFieldResponse.ProtoReflect.Descriptor instead.
func (*AddMetadataFieldResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{13}
}

type RemoveMetadataFieldRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field to remove; the kind and its identifying fields must match.
	Field         *MetadataField `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMetadataFieldRequest) Reset() {
	*x = RemoveMetadataFieldRequest{}
	mi := &file_assets_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMetadataFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMetadataFieldRequest) ProtoMessage() {}

func (x *RemoveMetadataFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMetadataFieldRequest.ProtoReflect.Descriptor instead.
func (*RemoveMetadataFieldRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveMetadataFieldRequest) GetField() *MetadataField {
	if x != nil {
		return x.Field
	}
	return nil
}

type RemoveMetadataFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMetadataFieldResponse) Reset() {
	*x = RemoveMetadataFieldResponse{}
	mi := &file_assets_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMetadataFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMetadataFieldResponse) ProtoMessage() {}

func (x *RemoveMetadataFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMetadataFieldResponse.ProtoReflect.Descriptor instead.
func (*RemoveMetadataFieldResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{15}
}

type TakedownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ns is the source namespace of the asset.
	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	// Id of the asset in the namespace's id scheme.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Version narrows the purge to a single version. Optional; the default
	// purges every version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// PinSelector pins the asset to this selector string at the edge
	// (e.g. "c-0.2-0.2-0.5-0.5"). Optional.
	PinSelector   string `protobuf:"bytes,4,opt,name=pin_selector,json=pinSelector,proto3" json:"pin_selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakedownRequest) Reset() {
	*x = TakedownRequest{}
	mi := &file_assets_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakedownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakedownRequest) ProtoMessage() {}

func (x *TakedownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakedownRequest.ProtoReflect.Descriptor instead.
func (*TakedownRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{16}
}

func (x *TakedownRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *TakedownRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TakedownRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TakedownRequest) GetPinSelector() string {
	if x != nil {
		return x.PinSelector
	}
	return ""
}

type TakedownResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DeletedObjects is the number of derivatives removed from the bucket.
	DeletedObjects int64 `protobuf:"varint,1,opt,name=deleted_objects,json=deletedObjects,proto3" json:"deleted_objects,omitempty"`
	// InvalidationId of the CDN invalidation, empty when the service runs
	// without a CDN distribution configured.
	InvalidationId string `protobuf:"bytes,2,opt,name=invalidation_id,json=invalidationId,proto3" json:"invalidation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TakedownResponse) Reset() {
	*x = TakedownResponse{}
	mi := &file_assets_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakedownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakedownResponse) ProtoMessage() {}

func (x *TakedownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakedownResponse.ProtoReflect.Descriptor instead.
func (*TakedownResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{17}
}

func (x *TakedownResponse) GetDeletedObjects() int64 {
	if x != nil {
		return x.DeletedObjects
	}
	return 0
}

func (x *TakedownResponse) GetInvalidationId() string {
	if x != nil {
		return x.InvalidationId
	}
	return ""
}

type RemoveSelectorPinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ns is the source namespace of the asset.
	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	// Id of the asset in the namespace's id scheme.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSelectorPinRequest) Reset() {
	*x = RemoveSelectorPinRequest{}
	mi := &file_assets_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSelectorPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSelectorPinRequest) ProtoMessage() {}

func (x *RemoveSelectorPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSelectorPinRequest.ProtoReflect.Descriptor instead.
func (*RemoveSelectorPinRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveSelectorPinRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *RemoveSelectorPinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveSelectorPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSelectorPinResponse) Reset() {
	*x = RemoveSelectorPinResponse{}
	mi := &file_assets_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSelectorPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSelectorPinResponse) ProtoMessage() {}

func (x *RemoveSelectorPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSelectorPinResponse.ProtoReflect.Descriptor instead.
func (*RemoveSelectorPinResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{19}
}

type SetAudienceDenyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aud is the audience identifier.
	Aud string `protobuf:"bytes,1,opt,name=aud,proto3" json:"aud,omitempty"`
	// Denied adds the deny entry when true and removes it when false.
	Denied        bool `protobuf:"varint,2,opt,name=denied,proto3" json:"denied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAudienceDenyRequest) Reset() {
	*x = SetAudienceDenyRequest{}
	mi := &file_assets_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAudienceDenyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAudienceDenyRequest) ProtoMessage() {}

func (x *SetAudienceDenyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAudienceDenyRequest.ProtoReflect.Descriptor instead.
func (*SetAudienceDenyRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{20}
}

func (x *SetAudienceDenyRequest) GetAud() string {
	if x != nil {
		return x.Aud
	}
	return ""
}

func (x *SetAudienceDenyRequest) GetDenied() bool {
	if x != nil {
		return x.Denied
	}
	return false
}

type SetAudienceDenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAudienceDenyResponse) Reset() {
	*x = SetAudienceDenyResponse{}
	mi := &file_assets_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAudienceDenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAudienceDenyResponse) ProtoMessage() {}

func (x *SetAudienceDenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAudienceDenyResponse.ProtoReflect.Descriptor instead.
func (*SetAudienceDenyResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{21}
}

type WarmIntermediateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ns is the source namespace of the asset.
	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	// Id of the asset in the namespace's id scheme.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Version of the asset; defaults to the current version ("0").
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmIntermediateRequest) Reset() {
	*x = WarmIntermediateRequest{}
	mi := &file_assets_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmIntermediateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmIntermediateRequest) ProtoMessage() {}

func (x *WarmIntermediateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmIntermediateRequest.ProtoReflect.Descriptor instead.
func (*WarmIntermediateRequest) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{22}
}

func (x *WarmIntermediateRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *WarmIntermediateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WarmIntermediateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type WarmIntermediateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State is "queued" (population is pending, including when it already
	// was), "cached" (an intermediate already exists), or "disabled" (the
	// namespace doesn't use the intermediate cache — not an error, so
	// fire-and-forget callers stay quiet across config changes).
	State         string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmIntermediateResponse) Reset() {
	*x = WarmIntermediateResponse{}
	mi := &file_assets_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmIntermediateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmIntermediateResponse) ProtoMessage() {}

func (x *WarmIntermediateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmIntermediateResponse.ProtoReflect.Descriptor instead.
func (*WarmIntermediateResponse) Descriptor() ([]byte, []int) {
	return file_assets_service_proto_rawDescGZIP(), []int{23}
}

func (x *WarmIntermediateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_assets_service_proto protoreflect.FileDescriptor

var file_assets_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x07, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x65, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67,
	0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x6e, 0x6f, 0x74, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x6e, 0x6f, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x73, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x0d,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x78, 0x69, 0x66, 0x5f, 0x69, 0x66, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x69, 0x66, 0x49, 0x66, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x98,
	0x01, 0x0a, 0x0c, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x30, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x56, 0x0a, 0x1a, 0x49, 0x6e, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x43, 0x72, 0x6f, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x52, 0x0a, 0x1b, 0x49, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x43, 0x72, 0x6f, 0x70,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e,
	0x44, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x07, 0x64, 0x72,
	0x6f, 0x70, 0x70, 0x65, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x50, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x22, 0x4b, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x30, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x22, 0x1a, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4e, 0x0a,
	0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x74, 0x61,
	0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x1d, 0x0a,
	0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6e, 0x0a, 0x0f,
	0x54, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x69, 0x6e,
	0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x69, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x64, 0x0a, 0x10,
	0x54, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x3a, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1b,
	0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x50, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x42, 0x0a, 0x16, 0x53,
	0x65, 0x74, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x6e, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x75, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x75, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6e, 0x69, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x22,
	0x19, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x44, 0x65,
	0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x53, 0x0a, 0x17, 0x57, 0x61,
	0x72, 0x6d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x30, 0x0a, 0x18, 0x57, 0x61, 0x72, 0x6d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x32, 0xb3, 0x01, 0x0a, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x22, 0x2e, 0x74,
	0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x94, 0x06, 0x0a, 0x0a, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x08, 0x54, 0x61, 0x6b, 0x65, 0x64, 0x6f,
	0x77, 0x6e, 0x12, 0x1c, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x2e, 0x54, 0x61, 0x6b, 0x65, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x54,
	0x61, 0x6b, 0x65, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x62, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x50, 0x69, 0x6e, 0x12, 0x25, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x74, 0x74,
	0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e,
	0x63, 0x65, 0x44, 0x65, 0x6e, 0x79, 0x12, 0x23, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65,
	0x44, 0x65, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x74,
	0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x75, 0x64,
	0x69, 0x65, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5f, 0x0a, 0x10, 0x57, 0x61, 0x72, 0x6d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x2e, 0x57, 0x61, 0x72, 0x6d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x74, 0x74,
	0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x57, 0x61, 0x72, 0x6d, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x65, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x26, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x41, 0x64, 0x64,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x24, 0x2e,
	0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x13, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x27, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x74, 0x74, 0x61,
	0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x13, 0x49, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x43,
	0x72, 0x6f, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x27, 0x2e, 0x74, 0x74,
	0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x70, 0x65, 0x63,
	0x74, 0x43, 0x72, 0x6f, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x74, 0x74, 0x61, 0x62, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x43, 0x72, 0x6f, 0x70, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x74, 0x61,
	0x62, 0x2f, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2d, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_assets_service_proto_rawDescOnce sync.Once
	file_assets_service_proto_rawDescData = file_assets_service_proto_rawDesc
)

func file_assets_service_proto_rawDescGZIP() []byte {
	file_assets_service_proto_rawDescOnce.Do(func() {
		file_assets_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_assets_service_proto_rawDescData)
	})
	return file_assets_service_proto_rawDescData
}

var file_assets_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_assets_service_proto_goTypes = []any{
	(*GetSigningKeysRequest)(nil),       // 0: ttab.assets.GetSigningKeysRequest
	(*GetSigningKeysResponse)(nil),      // 1: ttab.assets.GetSigningKeysResponse
	(*GetVariantsRequest)(nil),          // 2: ttab.assets.GetVariantsRequest
	(*GetVariantsResponse)(nil),         // 3: ttab.assets.GetVariantsResponse
	(*Variant)(nil),                     // 4: ttab.assets.Variant
	(*SigningKey)(nil),                  // 5: ttab.assets.SigningKey
	(*MetadataField)(nil),               // 6: ttab.assets.MetadataField
	(*DroppedField)(nil),                // 7: ttab.assets.DroppedField
	(*InspectCropMetadataRequest)(nil),  // 8: ttab.assets.InspectCropMetadataRequest
	(*InspectCropMetadataResponse)(nil), // 9: ttab.assets.InspectCropMetadataResponse
	(*ListMetadataFieldsRequest)(nil),   // 10: ttab.assets.ListMetadataFieldsRequest
	(*ListMetadataFieldsResponse)(nil),  // 11: ttab.assets.ListMetadataFieldsResponse
	(*AddMetadataFieldRequest)(nil),     // 12: ttab.assets.AddMetadataFieldRequest
	(*AddMetadataFieldResponse)(nil),    // 13: ttab.assets.AddMetadataFieldResponse
	(*RemoveMetadataFieldRequest)(nil),  // 14: ttab.assets.RemoveMetadataFieldRequest
	(*RemoveMetadataFieldResponse)(nil), // 15: ttab.assets.RemoveMetadataFieldResponse
	(*TakedownRequest)(nil),             // 16: ttab.assets.TakedownRequest
	(*TakedownResponse)(nil),            // 17: ttab.assets.TakedownResponse
	(*RemoveSelectorPinRequest)(nil),    // 18: ttab.assets.RemoveSelectorPinRequest
	(*RemoveSelectorPinResponse)(nil),   // 19: ttab.assets.RemoveSelectorPinResponse
	(*SetAudienceDenyRequest)(nil),      // 20: ttab.assets.SetAudienceDenyRequest
	(*SetAudienceDenyResponse)(nil),     // 21: ttab.assets.SetAudienceDenyResponse
	(*WarmIntermediateRequest)(nil),     // 22: ttab.assets.WarmIntermediateRequest
	(*WarmIntermediateResponse)(nil),    // 23: ttab.assets.WarmIntermediateResponse
}
var file_assets_service_proto_depIdxs = []int32{
	5,  // 0: ttab.assets.GetSigningKeysResponse.keys:type_name -> ttab.assets.SigningKey
	4,  // 1: ttab.assets.GetVariantsResponse.variants:type_name -> ttab.assets.Variant
	6,  // 2: ttab.assets.DroppedField.field:type_name -> ttab.assets.MetadataField
	7,  // 3: ttab.assets.InspectCropMetadataResponse.dropped:type_name -> ttab.assets.DroppedField
	6,  // 4: ttab.assets.ListMetadataFieldsResponse.fields:type_name -> ttab.assets.MetadataField
	6,  // 5: ttab.assets.AddMetadataFieldRequest.field:type_name -> ttab.assets.MetadataField
	6,  // 6: ttab.assets.RemoveMetadataFieldRequest.field:type_name -> ttab.assets.MetadataField
	0,  // 7: ttab.assets.Keys.GetSigningKeys:input_type -> ttab.assets.GetSigningKeysRequest
	2,  // 8: ttab.assets.Keys.GetVariants:input_type -> ttab.assets.GetVariantsRequest
	16, // 9: ttab.assets.Management.Takedown:input_type -> ttab.assets.TakedownRequest
	18, // 10: ttab.assets.Management.RemoveSelectorPin:input_type -> ttab.assets.RemoveSelectorPinRequest
	20, // 11: ttab.assets.Management.SetAudienceDeny:input_type -> ttab.assets.SetAudienceDenyRequest
	22, // 12: ttab.assets.Management.WarmIntermediate:input_type -> ttab.assets.WarmIntermediateRequest
	10, // 13: ttab.assets.Management.ListMetadataFields:input_type -> ttab.assets.ListMetadataFieldsRequest
	12, // 14: ttab.assets.Management.AddMetadataField:input_type -> ttab.assets.AddMetadataFieldRequest
	14, // 15: ttab.assets.Management.RemoveMetadataField:input_type -> ttab.assets.RemoveMetadataFieldRequest
	8,  // 16: ttab.assets.Management.InspectCropMetadata:input_type -> ttab.assets.InspectCropMetadataRequest
	1,  // 17: ttab.assets.Keys.GetSigningKeys:output_type -> ttab.assets.GetSigningKeysResponse
	3,  // 18: ttab.assets.Keys.GetVariants:output_type -> ttab.assets.GetVariantsResponse
	17, // 19: ttab.assets.Management.Takedown:output_type -> ttab.assets.TakedownResponse
	19, // 20: ttab.assets.Management.RemoveSelectorPin:output_type -> ttab.assets.RemoveSelectorPinResponse
	21, // 21: ttab.assets.Management.SetAudienceDeny:output_type -> ttab.assets.SetAudienceDenyResponse
	23, // 22: ttab.assets.Management.WarmIntermediate:output_type -> ttab.assets.WarmIntermediateResponse
	11, // 23: ttab.assets.Management.ListMetadataFields:output_type -> ttab.assets.ListMetadataFieldsResponse
	13, // 24: ttab.assets.Management.AddMetadataField:output_type -> ttab.assets.AddMetadataFieldResponse
	15, // 25: ttab.assets.Management.RemoveMetadataField:output_type -> ttab.assets.RemoveMetadataFieldResponse
	9,  // 26: ttab.assets.Management.InspectCropMetadata:output_type -> ttab.assets.InspectCropMetadataResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_assets_service_proto_init() }
func file_assets_service_proto_init() {
	if File_assets_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_assets_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_assets_service_proto_goTypes,
		DependencyIndexes: file_assets_service_proto_depIdxs,
		MessageInfos:      file_assets_service_proto_msgTypes,
	}.Build()
	File_assets_service_proto = out.File
	file_assets_service_proto_rawDesc = nil
	file_assets_service_proto_goTypes = nil
	file_assets_service_proto_depIdxs = nil
}
