// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: assets/service.proto

package assetsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	assets "github.com/ttab/elephant-public-api/assets"
	http "net/http"
)

// NewKeysServiceHandler builds an HTTP handler for the elephant.assets.Keys service from an
// implementation of the plain assets.Keys interface, and returns the path to mount it on together
// with the handler, just like NewKeysHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewKeysServiceHandler(svc assets.Keys, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewKeysHandler(&keysServiceHandler{svc: svc}, opts...)
}

// keysServiceHandler implements KeysHandler on top of a assets.Keys.
type keysServiceHandler struct {
	svc assets.Keys
}

func (h *keysServiceHandler) GetSigningKeys(ctx context.Context, req *connect.Request[assets.GetSigningKeysRequest]) (*connect.Response[assets.GetSigningKeysResponse], error) {
	res, err := h.svc.GetSigningKeys(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *keysServiceHandler) GetVariants(ctx context.Context, req *connect.Request[assets.GetVariantsRequest]) (*connect.Response[assets.GetVariantsResponse], error) {
	res, err := h.svc.GetVariants(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *keysServiceHandler) SignURL(ctx context.Context, req *connect.Request[assets.SignURLRequest]) (*connect.Response[assets.SignURLResponse], error) {
	res, err := h.svc.SignURL(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewKeysServiceClient constructs a client for the elephant.assets.Keys service that implements the
// plain assets.Keys interface, so that it is a drop-in for the Twirp clients. The options are the
// ones NewKeysClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewKeysServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) assets.Keys {
	return &keysServiceClient{
		client: NewKeysClient(httpClient, baseURL, opts...),
	}
}

// keysServiceClient implements assets.Keys on top of a KeysClient.
type keysServiceClient struct {
	client KeysClient
}

func (c *keysServiceClient) GetSigningKeys(ctx context.Context, req *assets.GetSigningKeysRequest) (*assets.GetSigningKeysResponse, error) {
	res, err := c.client.GetSigningKeys(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *keysServiceClient) GetVariants(ctx context.Context, req *assets.GetVariantsRequest) (*assets.GetVariantsResponse, error) {
	res, err := c.client.GetVariants(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *keysServiceClient) SignURL(ctx context.Context, req *assets.SignURLRequest) (*assets.SignURLResponse, error) {
	res, err := c.client.SignURL(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewManagementServiceHandler builds an HTTP handler for the elephant.assets.Management service
// from an implementation of the plain assets.Management interface, and returns the path to mount it
// on together with the handler, just like NewManagementHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewManagementServiceHandler(svc assets.Management, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewManagementHandler(&managementServiceHandler{svc: svc}, opts...)
}

// managementServiceHandler implements ManagementHandler on top of a assets.Management.
type managementServiceHandler struct {
	svc assets.Management
}

func (h *managementServiceHandler) Takedown(ctx context.Context, req *connect.Request[assets.TakedownRequest]) (*connect.Response[assets.TakedownResponse], error) {
	res, err := h.svc.Takedown(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *managementServiceHandler) RemoveSelectorPin(ctx context.Context, req *connect.Request[assets.RemoveSelectorPinRequest]) (*connect.Response[assets.RemoveSelectorPinResponse], error) {
	res, err := h.svc.RemoveSelectorPin(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *managementServiceHandler) SetAudienceDeny(ctx context.Context, req *connect.Request[assets.SetAudienceDenyRequest]) (*connect.Response[assets.SetAudienceDenyResponse], error) {
	res, err := h.svc.SetAudienceDeny(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *managementServiceHandler) WarmIntermediate(ctx context.Context, req *connect.Request[assets.WarmIntermediateRequest]) (*connect.Response[assets.WarmIntermediateResponse], error) {
	res, err := h.svc.WarmIntermediate(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *managementServiceHandler) ListMetadataFields(ctx context.Context, req *connect.Request[assets.ListMetadataFieldsRequest]) (*connect.Response[assets.ListMetadataFieldsResponse], error) {
	res, err := h.svc.ListMetadataFields(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *managementServiceHandler) AddMetadataField(ctx context.Context, req *connect.Request[assets.AddMetadataFieldRequest]) (*connect.Response[assets.AddMetadataFieldResponse], error) {
	res, err := h.svc.AddMetadataField(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *managementServiceHandler) RemoveMetadataField(ctx context.Context, req *connect.Request[assets.RemoveMetadataFieldRequest]) (*connect.Response[assets.RemoveMetadataFieldResponse], error) {
	res, err := h.svc.RemoveMetadataField(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *managementServiceHandler) InspectCropMetadata(ctx context.Context, req *connect.Request[assets.InspectCropMetadataRequest]) (*connect.Response[assets.InspectCropMetadataResponse], error) {
	res, err := h.svc.InspectCropMetadata(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewManagementServiceClient constructs a client for the elephant.assets.Management service that
// implements the plain assets.Management interface, so that it is a drop-in for the Twirp clients.
// The options are the ones NewManagementClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewManagementServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) assets.Management {
	return &managementServiceClient{
		client: NewManagementClient(httpClient, baseURL, opts...),
	}
}

// managementServiceClient implements assets.Management on top of a ManagementClient.
type managementServiceClient struct {
	client ManagementClient
}

func (c *managementServiceClient) Takedown(ctx context.Context, req *assets.TakedownRequest) (*assets.TakedownResponse, error) {
	res, err := c.client.Takedown(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *managementServiceClient) RemoveSelectorPin(ctx context.Context, req *assets.RemoveSelectorPinRequest) (*assets.RemoveSelectorPinResponse, error) {
	res, err := c.client.RemoveSelectorPin(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *managementServiceClient) SetAudienceDeny(ctx context.Context, req *assets.SetAudienceDenyRequest) (*assets.SetAudienceDenyResponse, error) {
	res, err := c.client.SetAudienceDeny(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *managementServiceClient) WarmIntermediate(ctx context.Context, req *assets.WarmIntermediateRequest) (*assets.WarmIntermediateResponse, error) {
	res, err := c.client.WarmIntermediate(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *managementServiceClient) ListMetadataFields(ctx context.Context, req *assets.ListMetadataFieldsRequest) (*assets.ListMetadataFieldsResponse, error) {
	res, err := c.client.ListMetadataFields(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *managementServiceClient) AddMetadataField(ctx context.Context, req *assets.AddMetadataFieldRequest) (*assets.AddMetadataFieldResponse, error) {
	res, err := c.client.AddMetadataField(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *managementServiceClient) RemoveMetadataField(ctx context.Context, req *assets.RemoveMetadataFieldRequest) (*assets.RemoveMetadataFieldResponse, error) {
	res, err := c.client.RemoveMetadataField(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *managementServiceClient) InspectCropMetadata(ctx context.Context, req *assets.InspectCropMetadataRequest) (*assets.InspectCropMetadataResponse, error) {
	res, err := c.client.InspectCropMetadata(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
